Shuttle Console Radar improvements
new-frontiers-14/frontier-station-14 pull request #1040
Opened 2024-02-20 16:35 UTC by GreaseMonk

## About the PR

Theres big changes to the map from this PR https://github.com/space-wizards/space-station-14/pull/24430
but it has a long time to go until it gets here.

- Added blips / triangles over ships and points towards ships when its outside radar circle
- Reduced font size
- dont show decimals for distance if >50m
- 1295m -> 1.3km  shows km's now instead of m to save some screen space
- added hover mouse over

Old:
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/1354802/b9f906f8-c25f-4dde-954d-47568caa25cb)

new:
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/1354802/0fd168b3-0a03-4a53-937c-e9e0f1470484)

## Why / Balance

figured i can make some QOL improvements to current radar

## Technical details

## Media

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

tweak: Radar QOL improvements

2024-02-21 02:59 UTC, exincore commented
The isosceles triangles at the rim of the radar view are rotated 120 degrees clockwise.

2024-02-21 03:15 UTC, exincore commented
The mouse position is different on different UI scales

2024-02-21 10:24 UTC, exincore commented
I did some more testing and it seems less to do with scaling and more to do with the offset?

2024-02-25 22:09 UTC, Cheackraze requested changes
looks good to me, though this is above me in many places. I only ask that any changes to upstream code have comments added in-line or block style denoting its a frontier change, along with a 1 sentence overview of the change if possible. This is so that maintainers can more easily spot and recognize necessary changes to the code.

2024-02-25 22:09 UTC, Cheackraze commented on Content.Client/Shuttles/UI/RadarControl.cs
> +    private const int RadarFontSize = 10;
possibly move these to the component in the future

2024-02-25 22:12 UTC, Cheackraze commented on Content.Client/Shuttles/UI/RadarControl.cs
> +    private const int RadarFontSize = 10;
not necessary for this PR though

2024-02-26 14:31 UTC, merged