nerf heavy armor
new-frontiers-14/frontier-station-14 pull request #113
Opened 2023-07-30 03:55 UTC by Leander-0

Nerfs Heavy Armor, ideally the solution would be to change the rewards given in the expeditions, but for now this will help to mitigate the fact that you can freely get an armor better then the deathsquad one without any significant speed slowdown, it will still be a good armor and reward but wont have use in space because its not insulated to the cold or pressure it.

***The old stats***
>80% Blunt
>80% Slash
>80% Piercing
>50% Heat
>100% Radiation lmao
>15% Caustic

***New stats***
>40% Blunt
>40% Slash
>50% Piercing
>30% Heat
>Removed radiation resistance.
>15% Caustic
>30% Explotion Resistance Added

**Changelog**

:cl:

- tweak: Nerfs Heavy armor

2023-07-30 23:26 UTC, dvir001 requested changes
Please add the
Radiation: 1
back so it wont eat it from the base armor.

2023-07-31 00:35 UTC, Leander-0 commented
![20230730_203358](https://github.com/new-frontiers-14/frontier-station-14/assets/80334192/9aba2a61-c0da-4382-bc24-15a22990f332)

it parents from this ones, none add radiation damage or take it away.

2023-07-31 00:48 UTC, dvir001 commented
> ![20230730_203358](https://user-images.githubusercontent.com/80334192/257084001-9aba2a61-c0da-4382-bc24-15a22990f332.png)
> 
> it parents from this ones, none add radiation damage or take it away.

Then one day upstream add base rad stat to it and fuck it like the warden armor with the speed issue.

2023-07-31 10:42 UTC, Cheackraze approved these changes

2023-07-31 10:42 UTC, merged