Any languages names
new-frontiers-14/frontier-station-14 pull request #119
Opened 2023-07-30 22:26 UTC by OCOtheOmega

## About the PR

New frontiers is also popular in non-English speaking countries, so why not make more diversity of languages? For rp situations it is useful when a player plays a Spaniard, Italian, Russian. For forks it will make less problems in translation, they will not need to customize support for names in other languages.

**Media**

![изображение](https://github.com/new-frontiers-14/frontier-station-14/assets/42233446/2abb064b-c219-412e-8083-8818abcbf703)
![изображение](https://github.com/new-frontiers-14/frontier-station-14/assets/42233446/ab8ff861-6d55-47ef-b966-f88f94102ffe)
![изображение](https://github.com/new-frontiers-14/frontier-station-14/assets/42233446/29e23a48-5dd2-42de-9f59-9210570abce3)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

:cl:
- tweak: Names on any languages!

2023-07-30 22:29 UTC, lexs0sa commented
Non-English shouldn't be used on English servers, there have already been issues with people naming themselves slurs in languages that couldn't be moderated.

2023-07-30 22:42 UTC, Cheackraze requested changes

2023-07-30 22:42 UTC, Cheackraze commented on Content.Shared/CCVar/CCVars.cs
> +            CVarDef.Create("ic.restricted_names", false, CVar.SERVER | CVar.REPLICATED);
please keep this true, and other servers can override to false on their own config.toml.  The basic game mode is designed for RP so this should be default on.

2023-07-31 06:57 UTC, Cheackraze approved these changes

2023-07-31 06:57 UTC, merged

2023-07-31 06:58 UTC, Cheackraze commented
contact me on discord for contributor role

2023-08-01 07:30 UTC, sTiKyt commented
> Non-English shouldn't be used on English servers, there have already been issues with people naming themselves slurs in languages that couldn't be moderated.

No worries, we have enough players to both, name themselves slurs, and to report those names :laughing: :ok_hand: