Mining asteroids overhaul
new-frontiers-14/frontier-station-14 pull request #1373
Opened 2024-05-16 20:42 UTC by Vonsant

## About the PR

## Why / Balance

## How to test

## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2024-05-16 20:45 UTC, dvir001 commented
Nice, Ill try and get it organized into _NF if you need help

2024-05-16 20:47 UTC, Vonsant commented
> Nice, Ill try and get it organized into _NF if you need help

If you think it will the best option, I have nothing against.
I'm just update files right now, so its not everything done right now/

2024-05-17 00:30 UTC, Vonsant commented
> Nice, Ill try and get it organized into _NF if you need help

Welp, i've did my best. Do you wanna change something?

2024-05-17 02:04 UTC, Vonsant commented
![mimicgif](https://github.com/new-frontiers-14/frontier-station-14/assets/118206719/99eb6762-8d8e-4214-8bca-32376b0a271d)
![68d16e6ca446f77b99e447fc2bc3ed3f](https://github.com/new-frontiers-14/frontier-station-14/assets/118206719/dd3ed78d-f48c-4c74-bf52-5741ec6c48a1)

Maybe next time it will be Wreck update. Maybe... Sometimes... When I can make upstream... There is no more Bears in space... No one hear your scream, when you find not just a regular crap on wreck.

2024-05-17 08:58 UTC, Vonsant commented
ffs

2024-05-17 10:01 UTC, Vonsant commented
Ok, now it's done.

2024-05-17 23:35 UTC, Cheackraze commented
nice, theyve needed some love for a long time

2024-05-17 23:40 UTC, Cheackraze requested changes
everything looks fine, just need everything moved to _NF/ folders

2024-05-18 23:22 UTC, Vonsant commented
I think it's done now?

2024-05-18 23:25 UTC, dvir001 commented
I'll have a look this week, going to clean some issues with the code before we add more stuff

Looking great 👍

2024-05-20 20:08 UTC, Cheackraze approved these changes
looks good for the most part, pretty much all yml. If one of the other maintainers doesnt give it a test run, I will sometime this week and we will get this in.

2024-05-20 20:10 UTC, dvir001 commented
> looks good for the most part, pretty much all yml. If one of the other maintainers doesnt give it a test run, I will sometime this week and we will get this in.

Wait a bit we want to clean the yml

2024-05-23 19:28 UTC, whatston3 reviewed
Pretty excited for this, looks like an excellent feature - I think the changes would help give variety and some additional needed lethality to salvage gameplay and should give medics a good bit more work.  The variety of asteroid types with different resource distributions is also great and allows for science vessel pilots to pick and choose when short on a resource.

My only gripe with this so far is that it's hard to tell when the golems are dead.  Even an edited, darker sprite as a placeholder would make threat assessment easier.

2024-05-24 00:32 UTC, dvir001 commented
It is done.

2024-05-24 15:00 UTC, whatston3 reviewed
Looks good so far.  Haven't reviewed the latest changes in their entirety, but a few comments and suggestions from what I've seen.

2024-05-24 15:00 UTC, whatston3 commented on Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
> +            orGroup: rock
```suggestion
            orGroup: rock
    - type: IFF
      flags: HideLabel
      color: "#b5b5b5"
```

Basalt rocks currently inherit their map colour from the base.  This suggested colour is a grey, to match the grey of the rock.  How this looks in-game:
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/49aa4b1b-62a3-4172-8ffc-940880f23f2d)
The rock is readable against the UI rings and the nearby Pioneer's outline.

2024-05-24 15:00 UTC, whatston3 commented on Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
> +      color: "#7d75bf"
```suggestion
      color: "#8178cc"
```

Chromite asteroids show up as a bit dark on the radar.  This makes them slightly easier to read.  In-game:
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/8448dfed-0fe7-40e7-96d8-5450715f9b4e)
Should better stand out against the background and be readily distinguishable from wrecks.

2024-05-24 15:01 UTC, whatston3 commented on Resources/Prototypes/_NF/Entities/World/Debris/asteroids.yml
> +      color: "#d67e27"
I don't think I've seen an instance of this asteroid type spawned.  I'll look into it a bit more when I can.

2024-05-24 19:44 UTC, Cheackraze commented
I agree with whatson, and if this is ready I'd like to get it in for the weekend

2024-05-24 19:53 UTC, dvir001 commented
> I agree with whatson, and if this is ready I'd like to get it in for the weekend

You can approve the segested changes, I won't have time to test it again today.

2024-05-24 20:28 UTC, merged