Multicoloured spesos: add layer function in StackComponent
new-frontiers-14/frontier-station-14 pull request #1496
Opened 2024-06-10 14:31 UTC by whatston3

## About the PR

Spesos should now appear in non-single denominations.

StackComponents now have an optional layerFunction that will adjust the layer data before it is used in the StackVisualizer.

This is only used in spesos stacks at the moment, with one concrete instance that uses threshold values (used with bill denominations for the purpose of spesos).

## Why / Balance

Looks pretty, feels better when you make more money.

My biggest concerns here are whether this is fragile with respect to upstream changes, and if the names of things make sense.

## How to test

Build and run local server.
1. Spawn in spesos in $1, $10, $100, $500, $1000, and $1000000 denominations.
2. Try merging and splitting 1 off from all bills larger than $1.

## Media

![spesos](https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/e52cd713-e79f-4e6f-a9fc-b39c340790e2)

- [X] ***I have added screenshots/videos to this PR showcasing its changes ingame***, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- fix: Stacks of spesos now display the largest valued bill on top.

2024-06-10 14:36 UTC, dvir001 commented
Can you also cap the stack to max $1000000 / 100000 ?
Might as well since its a bit weird you can have infinite amounts on a single stack

2024-06-10 14:40 UTC, whatston3 commented
> Can you also cap the stack to max $1000000 / 100000 ? Might as well since its a bit weird you can have infinite amounts on a single stack

I'll look into how this works with cargo sales and ATM withdrawals, not the largest fan of the idea, makes handling large transfers (e.g. spessman's lotto) awkward.

2024-06-10 14:50 UTC, Leander-0 commented
I like the idea of the money being stacked, we can add money bags that act as the mining bags to handle large amounts of money. kinda silly that one can carry 1 million spessos on their pocket without issue. also adds gameplay to hide the money from pirates.

2024-06-10 17:44 UTC, whatston3 commented
> I'll look into how this works with cargo sales and ATM withdrawals, not the largest fan of the idea, makes handling large transfers (e.g. spessman's lotto) awkward.

Gonna say this is out of the scope of the PR.  Capping the max stack size causes issues with ATM withdrawal ("admin, help, I asked for 5 million spesos, ATM gave me 1 and ate the other 4").  What I'd argue _is_ in scope is a few new bill denominations (10K, 25K, 50K, and 100K all scroll - space on bill face for amount is tiny - but do not change colour).  Pink bill needs rework, my spriteing is awful.

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/c60f0894-0a50-4542-9a77-15f6ae5f7f2b)

2024-06-10 22:27 UTC, dvir001 commented
> > I'll look into how this works with cargo sales and ATM withdrawals, not the largest fan of the idea, makes handling large transfers (e.g. spessman's lotto) awkward.
> 
> Gonna say this is out of the scope of the PR. Capping the max stack size causes issues with ATM withdrawal ("admin, help, I asked for 5 million spesos, ATM gave me 1 and ate the other 4"). What I'd argue _is_ in scope is a few new bill denominations (10K, 25K, 50K, and 100K all scroll - space on bill face for amount is tiny - but do not change colour). Pink bill needs rework, my spriteing is awful.
> 
> ![image](https://private-user-images.githubusercontent.com/166147148/338288143-c60f0894-0a50-4542-9a77-15f6ae5f7f2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNTg3NjAsIm5iZiI6MTcxODA1ODQ2MCwicGF0aCI6Ii8xNjYxNDcxNDgvMzM4Mjg4MTQzLWM2MGYwODk0LTBhNTAtNDU0Mi05YTc3LTE1ZjZhZTVmN2YyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMFQyMjI3NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjBjNjdjMjcwODM1M2MyYzhkYjA3OWM2OWE0ODI5ZGRlYzc1NWY4YmM4OGZmMDY3NjNiNTg3NWZlMDMyNTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5yodm3-I0DHJicHyQ6CcZ9uE3mOyrhTCqkLbKbMMG4w)

Sound good

2024-06-10 23:11 UTC, whatston3 commented
Adjusted style of large bills:
* all scroll left
* all use 4-pixel wide zeros
* colours avoid repetition as best as possible
* pink bill changed to a bright red [still probably too bright]
* rainbow bill flashing follows order of currency, uses buff colour at bottom of digits
* rainbow bill value changed to 250k (rationale here: if we will have a maximum size at some point, you shouldn't be able to hide your flashing bills easily by splitting it easily

Preview of bills as they stand (bottom row are animated - 10k, 25k, 50k, 100k, 250k+)
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/166147148/4ce97087-4046-41c9-9d67-a8d6ba4fac5b)

2024-06-13 23:26 UTC, Cheackraze requested changes

2024-06-13 23:26 UTC, Cheackraze commented on Content.Shared/Stacks/StackComponent.cs
> +        public StackLayerFunction? LayerFunction;
hm this seems really smelly to me. It seems like you're storing a function into a component, which isnt serializable and will break any kind of saving/loading or serialization. The benefits of keeping components to only data, and a fully ECS system.

2024-06-13 23:26 UTC, Cheackraze commented on Content.Client/Stack/StackSystem.cs
> +                comp.LayerFunction.Apply(ref data); // Frontier
instead, you should just add a bool flag to the stack component to check for that instead, and then call the shared function here after bringing it in as a dependency.

2024-06-14 03:52 UTC, whatston3 commented
Will review this with fresher eyes before requesting another review, but @Cheackraze, your concerns should be addressed.

2024-06-14 22:21 UTC, whatston3 commented
Changes should be addressed.  Still functional, and if you have a better name for `ThresholdStackLayerFunctionComponent`, I'm all ears.

2024-06-14 22:49 UTC, Cheackraze commented
> Changes should be addressed. Still functional, and if you have a better name for `ThresholdStackLayerFunctionComponent`, I'm all ears.

at is a bit wordy for what it is. Its just a component, its use for a function is irrelevant. maybe just, 'StackLayerThresholdComponent'

2024-06-14 22:58 UTC, whatston3 commented
> at is a bit wordy for what it is. Its just a component, its use for a function is irrelevant. maybe just, 'StackLayerThresholdComponent'

Sounds good to me.  Renamed file, reworded a comment, adjusted component name in speso YAML definition.  Still works alright, no issues.

2024-06-14 23:01 UTC, Cheackraze approved these changes

2024-06-14 23:17 UTC, merged