NFSD Bike for NFSD Fun Category
new-frontiers-14/frontier-station-14 pull request #1510
Opened 2024-06-13 15:33 UTC by BramvanZijp

## About the PR
Swaps the Civillian hoverbike in the fun part of the loadout tab for the NFSD Variant if playing an NFSD role, costs 25k.

## Why / Balance
Its an NFSD hoverbike, I feel like if you buy a bike roundstart as NFSD you should get it. And the 10k discount is because theres enough expenses on NFSD already anyway.

## How to test
Run the build in a release config and check the loadouts tab of any NFSD role if you have atleast 50 hours of playtime, it should show the NFSD bike under the fun tab instead of the civ one.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- tweak: The Hoverbike under the fun tab of the loadouts menu has been replaced with the NFSD variant for NFSD personell, keeping the 50 hours playtime requirement.

2024-06-13 15:40 UTC, dvir001 requested changes

2024-06-13 15:40 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
Ok find me another place in the code where NFSD isnt Nfsd on entity

Also isnt its a fucking insane over kill to add a full louadout just for this?

2024-06-13 15:40 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/fun.yml
> +  id: NFSDHoverbikeFlatpack
NFSD?
Nfsd

2024-06-13 15:40 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/Jobs/Contractor/fun.yml
> +  id: NFSDHoverbikeFlatpack
NFSD?
Nfsd

2024-06-13 15:44 UTC, whatston3 commented
I suppose the in-context question is who owns the hoverbike?  The one you get from an uplink is NFSD property, sure.  Is this a personal bring-along?  Isn't the rest of your NFSD gear free?

2024-06-13 15:46 UTC, whatston3 commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
Unfortunately:
`NFSDCriminalRecordsComputerCircuitboard`
`NFSDAdvancedRadarConsoleCircuitboard`

2024-06-13 15:47 UTC, dvir001 commented
Im not a fan of adding a full loadout setup just for a single item that exists on the uplink, this is more maintainer upkeep that we dont need.

You can just lower the price on the uplink if you see it as an issue.

2024-06-13 15:48 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻
This need a fix in a new PR

2024-06-13 15:51 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
> > Ok find me another place in the code where NFSD isnt Nfsd on entity
> > Also isnt its a fucking insane over kill to add a full loadout just for this?
> 
> As for the full loadout, unless you want hoverbikes to get their own tab, I dont see an easy way to do this. I made sure to keep the name of the tab the same, so its only a backend thing.

Honestly just lower the price on uplink

2024-06-13 15:52 UTC, BramvanZijp commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
> > > Ok find me another place in the code where NFSD isnt Nfsd on entity
> > > Also isnt its a fucking insane over kill to add a full loadout just for this?
> > 
> > 
> > As for the full loadout, unless you want hoverbikes to get their own tab, I dont see an easy way to do this. I made sure to keep the name of the tab the same, so its only a backend thing.
> 
> Honestly just lower the price on uplink

What would be a good price though? Like 2-3?

2024-06-13 15:57 UTC, dvir001 commented on Resources/Prototypes/_NF/Loadouts/contractor_loadout_groups.yml
> +  id: NFSDFun # Left Hand - 1 only, variant with the NFSD HoverBike.
> > > > Ok find me another place in the code where NFSD isnt Nfsd on entity
> > > > Also isnt its a fucking insane over kill to add a full loadout just for this?
> > > 
> > > 
> > > As for the full loadout, unless you want hoverbikes to get their own tab, I dont see an easy way to do this. I made sure to keep the name of the tab the same, so its only a backend thing.
> > 
> > 
> > Honestly just lower the price on uplink
> 
> What would be a good price though? Like 2-3?

Make it 3

2024-06-13 16:25 UTC, whatston3 commented
> Maybe theres a way to create a seperate loadout thats paranted by the fun tab and thus wouldnt require adding new items to both fun and nfsdfun?

If I understand you correctly, the issue is that you're modifying one of the data fields in the object - you can't say "inherit the parent's values and add these", you need to specify the entire set.

A separate question: what if the NFSD roles had _a bunch_ of NFSD-specific loadout items, maybe even between multiple loadout groups?  As it stands, you're proposing just the bike replacement, but what if there was a larger set of them?  e.g. NFSD balloon, handheld flag, toy sheriff's badge, maybe some commemorative NFSD pinpointer that points to the NFSD outpost.

2024-06-18 23:28 UTC, GiggIess commented
I must weigh in here as a player, I'm not a fan of this. I like to be able to buy a bike that lets me place and take off my own bag. The NFSD bikes are "upgraded" and forced to carry satchels, that you cannot remove.

2024-06-28 15:27 UTC, dvir001 commented
Price lowered to 3 on new upstream update soon :tm:

2024-06-28 15:27 UTC, closed without merging