Expedition Bestiary
new-frontiers-14/frontier-station-14 pull request #1548
Opened 2024-06-19 21:32 UTC by ErhardSteinhauer

## About the PR
Draft until https://github.com/new-frontiers-14/frontier-station-14/pull/1534 is merged
- Firsts draft of extended description for expedition game mode.
- Very rough draft layout of guidebook entries for expedition enemies (only aberrant flesh is somewhat filled out, the templae most likely will be changed, the rest left as blanks).
- Some bundled changes to monsters to make them slightly more diverse.

## Why / Balance
To give players information about game mechanics tied to expedition monsters.

## How to test
Open the guidebook

## Media
Later
- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Shouldn't be any

**Changelog**
:cl: erhardsteinhauer
- add: Guidebook entries for expedition enemies.

2024-06-23 21:19 UTC, ErhardSteinhauer commented
The PR is ready, all checks have passed. Going to put it back in draft until https://github.com/new-frontiers-14/frontier-station-14/pull/1534 is merged

2024-06-28 16:21 UTC, whatston3 requested changes
Partial review.  Still need to look through the enemy type entries, but looks good in-game from what I've seen.  Try to be a bit skeptical on the suggested changes.

Sorry it took so long to get to this.

2024-06-28 16:21 UTC, whatston3 commented on Resources/ServerInfo/_NF/Guidebook/Expeditions.xml
> +  ## Know your enemy
```suggestion
  Communication is crucial. Make sure to keep in contact with your teammates to know what they're doing and when they need help. You'll need either a headset and a [color=#a4885c]telecommunication server[/color] with [color=#a4885c]encryption keys[/color] installed, or [color=#a4885c]handheld radios[/color] on each crewmate (make sure they're on!).

  Having a [color=#a4885c]medical encryption key[/color] installed in your headset will tell you when anyone with a  [color=#a4885c]medical tracking implanter[/color] installed goes down in combat.  Leave no friend behind!
  
  ## Know Your Enemy
```

2024-06-28 16:21 UTC, whatston3 commented on Resources/ServerInfo/_NF/Guidebook/Expeditions.xml
> +  Adaptability is key: strategies and tactics that prove effective against [color=#a4885c]Xeno[/color] threats may not work at all against hostile [color=#a4885c]mercenaries[/color], and vice versa.
```suggestion
  Adaptability is key: strategies and tactics that work against [color=#a4885c]Xenos[/color] might not work well against [color=#a4885c]mercenaries[/color], and vice versa. The Guidebook entries on hostile entities may provide some insight into what to expect planetside, but they [italic]cannot[/italic] replace firsthand experience. Instead, descend to the planet, salvage what you can, and face danger head-on. The riches won't wait around forever!
```

2024-06-28 17:12 UTC, ErhardSteinhauer commented
I probably should use links whenever I mention specific factions in exped overview entry

2024-06-28 17:16 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_base.yml
> +    damageCap: 9999
No, it's there to make sure that health regen will be "always" active, no matter how far in the negatives mobs health is.

2024-06-28 17:18 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Mobs/NPCs/mob_hostile_expeditions_aberrant_flesh.yml
> +  id: MobFleshAssimilatedMiner
Haven't decided yet tbh. The rest of the mobs in this faction don't have unique names, so I kinda left this one without name too

2024-06-28 17:18 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Objects/Misc/space_cash.yml
> +- type: entity
Sounds good!

2024-06-28 17:20 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Mobs/NPCs/misc.yml
> +  name: "and that guy"
Yeah, good call. When I made those I wasn't sure how captions work in xml.

2024-06-28 17:27 UTC, ErhardSteinhauer commented on Resources/ServerInfo/_NF/Guidebook/Expeditions.xml
> +  - [bold]Rush:[/bold] you will have less time to complete the expedition. Set your priorities in advance and try to avoid wearing too much gear with negative speed modifiers.
fanning out - might not be the best advice.

2024-06-28 18:38 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Structures/Specific/punks.yml
> +          Quantity: 125
Added free non-taxable vent crud, space drugs, mopwata and acid spit

2024-06-30 10:11 UTC, ErhardSteinhauer commented on Resources/ServerInfo/_NF/Guidebook/Expeditions.xml
> +  - [bold]Rush:[/bold] you will have less time to complete the expedition. Set your priorities in advance and try to avoid wearing too much gear with negative speed modifiers.
added the rest

2024-07-05 12:26 UTC, dvir001 commented
Might want to remove the timers
This should be fixed on despawn code

2024-07-05 12:32 UTC, ErhardSteinhauer commented
> Might want to remove the timers This should be fixed on despawn code

Sure.

2024-07-05 12:47 UTC, ErhardSteinhauer commented
> Might want to remove the timers This should be fixed on despawn code

Done

2024-07-08 20:21 UTC, Cheackraze approved these changes

2024-07-08 20:49 UTC, merged