Smuggling Revamp: The Syndicate Broker
new-frontiers-14/frontier-station-14 pull request #1655
Opened 2024-07-11 20:26 UTC by Ed-Head

## About the PR

Adds 2 new jobs: The Syndicate Broker and Syndicate Bodyguard a soft antag group in charge of distributing dead drops from a POI they commandeer.
I wrote a more exhaustive description on the discord ideas section under the same name to prevent cluttering this PR.

Reworked the deaddrop system to allow printing jobs from fax machines that have the component while still allowing dead drop posters to exist.

Also as a note, the broker starting with cash is a band-aid fix until those NFSD ship vouchers get added because then I can just reskin one for the broker. The cheapest ship there costs 50K and sells for far less.

## Why / Balance

Smuggling as it is, is an RP wasteland, for both smugglers and NFSD. Not only that, making smuggling have greater ramifications for the sector as well as soft antag syndie jobs have been discussed and wished for ad-nauseam.
## How to test

Boot server and join as the Syndicate Broker, observe the new fax machine they start with. 
## Media

![broker](https://github.com/new-frontiers-14/frontier-station-14/assets/92019614/d2d576d9-5823-4105-8651-ac03c0989f3f)
![broker2](https://github.com/new-frontiers-14/frontier-station-14/assets/92019614/293f9f6f-173b-4bd2-a2af-db96cd18c2d1)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

add: The Syndicate is now hiring for a new "public relations" position at listening point bravo.

2024-07-12 04:04 UTC, ErhardSteinhauer commented
You deffo should link the discort convo before it's lost to ether

2024-07-12 04:42 UTC, Ed-Head commented
Good thinking

https://discord.com/channels/1123826877245694004/1261045523931074650

2024-07-12 04:48 UTC, Ed-Head commented
As it stands the outcome of the conversation can be summarized as 

- [ ] Add a contraband cargo catalogue to lpb that runs on telecrystals

- [ ] Add telecrystals to the dead drops

- [ ] reduce the distance dead drops spawn at

- [ ] Probably remove the IFF, the broker team probably cant get away with trying to hide a whole POI

- [ ] Make the NFSD channel tattle message more vague to give the team deniability

Im going to be whittling down these things over time, but of course feel free to let me know if you think up anything relevant to this. Also I guess this should probably be marked WIP or something until its ready at last.

2024-07-12 10:08 UTC, dvir001 commented on Resources/Prototypes/_NF/Roles/Jobs/Syndicate/syndicate_broker.yml
> +    - BriefcaseSyndicateBrokerBundleFilled
Cannot use suitstorage since fucking vox errors on next update (Even when its not a vox testing might fail)
You have to use loadouts or no bank.

2024-07-12 13:33 UTC, Salvantrix commented
Just gonna write this down so I don't forget, a neat take instead of taking over a POI could be the addition of a Syndicate fake mailman that then delivers the notes to the various POIs. Adding just a bit less chance its going to be meta'd by NFSD and adding some more dynamic shenanigans.

2024-07-13 17:05 UTC, whatston3 requested changes
Did a code review pass of it, left some thoughts.  Haven't yet tested it yet, but it's interesting.

Requesting changes for some cleanup, might have other thoughts later - need to come back to this.

2024-07-13 17:05 UTC, whatston3 commented on Content.Server/_NF/Smuggling/DeadDropSystem.cs
> +        args.Handled = SendDeadDrop(args.TargetUid, comp, uid, hands);
Shouldn't _really_ need a hand component in this case.  Maybe either the argument should be nullable and you pass null, or you have a fax-specific version of SendDeadDrop that omits it.

2024-11-11 17:23 UTC, Cheackraze commented
this is still a compelling direction to take the smuggling system, as of now we have the notices just being sent to a 'random' fax machine, but with the other smuggling changes that happened we are getting feedback to finalize and this would still make for an interesting gameplay option. My only concern is, how do we ensure that whoever takes the 'broker' role doesnt merely try to turn it into a solo experience and just do the smuggling themselves, and how we can make it so they are more running the poi and handing out the certs and not doing the smuggling themselves etc.

2024-11-11 17:37 UTC, dvir001 commented
Been putting work into smaller PR's to make it possible, as I talk to @Ed-Head one of the ideas will be to have a mailman syndicate with a syndicate bank to support more of a random aspect, with the edition of the option to buy specific items for re-selling base on packages delivered for more specific items.

2025-01-12 13:26 UTC, dvir001 commented
Im closing this for now but going to rework this PR right after we done with the MOM medical PR.

2025-01-12 13:26 UTC, closed without merging

2025-04-14 03:15 UTC, BlueNexus commented
Still planning to continue this?