Investigator (Update)
new-frontiers-14/frontier-station-14 pull request #1671
Opened 2024-07-14 08:14 UTC by ErhardSteinhauer

## About the PR
- Removed bar and microwave.
- Removed salvage equipment.
- Created separate engine room.
- Reworked atmos.
- Added guidebook entry with map.

## Why / Balance
Part of the ongoing push for limiting shuttles to single purpose. Investigator enjoyers had it too good for far too long.

## How to test
Buy NR Investigator and despair.

## Media
![2024-7-14_11 06 20](https://github.com/user-attachments/assets/8fdfdb91-0477-4f88-874d-9ddfff59a123)
![2024-7-14_11 06 04](https://github.com/user-attachments/assets/f4a284c1-df82-440a-a9d2-e160d53f437a)
![image](https://github.com/user-attachments/assets/4954cf7a-457d-412d-b703-3d20902b8c5f)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
Investigator powergaming

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated NR Investigator.

2024-07-14 08:15 UTC, ErhardSteinhauer commented
Ship owner: @UbaserB 
(Just tagging you to make sure you're aware there's suggested changes for you ship.)

2024-07-14 08:16 UTC, dvir001 commented
Might want to keep microwave just for the rads reactions

2024-07-14 08:17 UTC, ErhardSteinhauer commented
> Might want to keep microwave just for the rads reactions

They can research service branch and print microwave.
Or buy refined bananium.

2024-07-14 08:17 UTC, ErhardSteinhauer commented
Or spray it

2024-07-14 08:18 UTC, dvir001 commented
> > Might want to keep microwave just for the rads reactions
> 
> They can research service branch and print microwave. Or buy refined bananium.

Rads removed from it upstream and we probably just going to keep that change

2024-07-14 08:20 UTC, ErhardSteinhauer commented
> > > Might want to keep microwave just for the rads reactions
> > 
> > 
> > They can research service branch and print microwave. Or buy refined bananium.
> 
> Rads removed from it upstream and we probably just going to keep that change

Hm, riiiight. Still, research option is there.

2024-07-14 08:21 UTC, UbaserB commented
I don't like the tabletop computers, i prefer normal ones. Also, there's a shutter over the door in the control room. Other than that, lgtm

2024-07-14 08:22 UTC, ErhardSteinhauer commented
> I don't like the tabletop computers, i prefer normal ones. Also, there's a shutter over the door in the control room. Other than that, lgtm

Shutter over the door is intentional

2024-07-14 08:23 UTC, dvir001 commented
> > > > Might want to keep microwave just for the rads reactions
> > > 
> > > 
> > > They can research service branch and print microwave. Or buy refined bananium.
> > 
> > 
> > Rads removed from it upstream and we probably just going to keep that change
> 
> Hm, riiiight. Still, research option is there.

Fair

2024-07-14 08:23 UTC, UbaserB commented
> > I don't like the tabletop computers, i prefer normal ones. Also, there's a shutter over the door in the control room. Other than that, lgtm
> 
> Shutter over the door is intentional

I can see the idea you're going for, but generally please just keep the shutters external (so like, between the seating area and the control room, no shutters)

2024-07-14 08:27 UTC, ErhardSteinhauer commented
> but generally please just keep the shutters external

I disagree with this.
However, I don't have too strong feelings about it and I have editor opened right now, so I'll remove it.

2024-07-14 08:30 UTC, ErhardSteinhauer commented
![2024-7-14_11 30 10](https://github.com/user-attachments/assets/3d1c1169-49f7-4047-9161-7fc14ea364e5)

2024-07-14 14:34 UTC, ThatOneGoblin25 commented
Hi do you reckon you could semi-revert the artifact chamber from the old version to have a gap between the ship and the chamber?

![20240326211859!Investigator](https://github.com/user-attachments/assets/5eae4051-5d2e-4cac-878b-4ee34188ef4c)

I recently got told that the firelocks can be a bit of a death trap and I only made that change because the artifact analyse console had a smaller range.

2024-07-14 15:58 UTC, ErhardSteinhauer commented
I love me a good death trap. And I like the firelock setup there. But I'll think about it more.

2024-07-15 01:16 UTC, whatston3 commented on Resources/ServerInfo/_NF/Guidebook/Shipyard/Investigator.xml
> +  ** - Investigator-class research ships have higher power demand than standard P.A.C.M.A.N. generator unit can provide at optimal settings, however the ship comes equipped with additional P.A.C.M.A.
Small suggested rewrite.
```suggestion
  * - Investigator-class research ships are equipped with two APC units that can be used to appraise the ship's total power consumption. An unmodified Investigator-class ship requires 39.6 kW of power to remain operational.
  
  ** - Investigator-class research ships have higher power demand than standard P.A.C.M.A.N. generator unit can provide at optimal settings, however the ship comes equipped with additional P.A.C.M.A.N. generator unit and 67 solar panels that can provide up to 33.5 kW of power under ideal circumstances. Assuming that the solar array will provide a third of its maximum output power, recommended target power output for each P.A.C.M.A.N. generator unit is 15 kW.
```

2024-07-15 01:18 UTC, whatston3 requested changes
Changes seem sane, ship looks good.  Requested a small guidebook rewrite, otherwise, happy to approve.

2024-07-15 06:57 UTC, ErhardSteinhauer commented on Resources/ServerInfo/_NF/Guidebook/Shipyard/Investigator.xml
> +  ** - Investigator-class research ships have higher power demand than standard P.A.C.M.A.N. generator unit can provide at optimal settings, however the ship comes equipped with additional P.A.C.M.A.
Good stuff

2024-07-15 09:52 UTC, Dysh3s commented
No bar = no ATM. ATMs are placed at ships with bar\kitchens, iirc. Or so i heard.

2024-07-15 09:54 UTC, ErhardSteinhauer commented
> No bar = no ATM. ATMs are placed at ships with bar\kitchens, iirc. Or so i heard.

Not necessarily. In any case, the ATM is there to speed up the transactions between scientist and someone buying tech from them. (In rare case a scientist even cares to read the chat and sell something at all).

2024-07-15 10:01 UTC, Dysh3s commented
> > No bar = no ATM. ATMs are placed at ships with bar\kitchens, iirc. Or so i heard.
> 
> Not necessarily. In any case, the ATM is there to speed up the transactions between scientist and someone buying tech from them. (In rare case a scientist even cares to read the chat and sell something at all).

Yeah, that's exactly why i asked for ATM for all RND ships at some point and was answered that only ships with bars\kitchens had ATMs.

2024-07-15 10:58 UTC, Tych0theSynth commented
> > > No bar = no ATM. ATMs are placed at ships with bar\kitchens, iirc. Or so i heard.
> > 
> > 
> > Not necessarily. In any case, the ATM is there to speed up the transactions between scientist and someone buying tech from them. (In rare case a scientist even cares to read the chat and sell something at all).
> 
> Yeah, that's exactly why i asked for ATM for all RND ships at some point and was answered that only ships with bars\kitchens had ATMs.

Not sure how long ago that was, but no questions were raised about the Lyrae having an ATM when I PR'ed that. Doubt it's an issue any more, and it makes perfect sense for sci ships to have them.

2024-07-15 17:06 UTC, whatston3 approved these changes

2024-07-22 02:14 UTC, merged