Allow reapplying approved and denied stamps
new-frontiers-14/frontier-station-14 pull request #1695
Opened 2024-07-18 15:44 UTC by whatston3

## About the PR

Adds a Reapply field to StampComponent, StampDisplayInfo.

Any StampComponent (e.g. on pens, stamps) with their Reapply field set will allow those stamps to be reapplied.

## Why / Balance

Finally, papers please RP.

## How to test

1. Spawn approve stamp.
2. Spawn paper.
3. Stamp paper multiple times.
4. View paper.  Wow, so many stamps.
5. Spawn deny stamp.
6. Spawn paper.
7. Stamp paper multiple times.
8. View paper.  Wow, so many stamps.
9. Eject your pen.
10. Sign paper multiple times.
11. One signature.
12. Spawn QM stamp.
13. Stamp paper multiple times.
14. One stamp.

## Media

![approb](https://github.com/user-attachments/assets/e49ca98c-3466-4bd7-9f40-4ed68eefbe1c)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Approve and deny stamps can now be reapplied.

2024-07-18 15:50 UTC, dvir001 commented
How many times do I need to stamp with auto clicker before the server crash?

2024-07-18 16:56 UTC, whatston3 commented
> How many times do I need to stamp with auto clicker before the server crash?

Applied a maximum of 10 stampings for reapplied stamps (currently hardcoded in PaperSystem.cs), added a 1 second delay on stamps (feels reasonable, 1.5 and 2 were a bit long).  I've avoided the nasty list check for non-reapplied stamps.

2024-07-27 14:00 UTC, dvir001 requested changes
Line jumping on every stamp issue

2024-08-04 19:38 UTC, dvir001 approved these changes

2024-08-04 20:04 UTC, merged