Low pop food events
new-frontiers-14/frontier-station-14 pull request #1708
Opened 2024-07-19 18:58 UTC by dvir001

## About the PR
Fixed BluespaceCargoRule to be a single system, made it much more simple for adding new events based on it.
Added new 2 events for under 20 players:
Spawn 1-3 crates of McCargo (1-9 food boxes) on random ship.
Spawn a damaged McDelivery with 3 crates (3-9 food boxes)  in it, can happen 2 times in total.

## Why / Balance
Food for low pop in the case no one making any.

## How to test
addgamerule BluespaceMcCargo when you got a ship to get the random crates spawn
addgamerule BluespaceMcEvent to get the event to spawn

## Media
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

![image](https://github.com/user-attachments/assets/eeb7c997-734d-448c-9aa7-5a6abe25fc0e)

## Breaking changes
N/A

**Changelog**
:cl: dvir01
- add: Low pop of 20 and less might get free food from 2 new events now.

2024-07-19 22:58 UTC, whatston3 requested changes
Left a bunch of suggestions.  I've made them all on a branch on my repo ([whatston3:2024-07-19-FoodEvent-suggestions](https://github.com/whatston3/frontier-station-14/tree/2024-07-19-FoodEvent-suggestions)).  Event as-is seems generous for low-pop, but eh.

I did rename the Minimum/Maximum variable, I added snack food (chips, raisins, chocolate) to replace the onion rings and put them in the side group with the fries, and I set the maxOccurrences for the BluespaceMcCargo event to 3.

Not sure if you're a fan of the orGroup & amount solution for the BluespaceMcCargo distribution.  I did like the normalized prob settings, those were nice.

Something I didn't do - would it make sense if the events had different names?  `BluespaceMcCargoCrate` vs. `BluespaceBrokenMcDelivery`?

Works well, happy to approve when the suggestions are reviewed.

2024-07-19 22:58 UTC, whatston3 commented on Resources/Prototypes/Catalog/Fills/Crates/food.yml
> +      prob: 0.5
Should be moved under an _NF folder.

2024-07-19 23:07 UTC, dvir001 commented on Resources/Textures/_NF/Structures/Storage/Crates/mccargo.rsi/meta.json
> +  "copyright": "Created by EmoGarbage404 (github) and modified by Potato1234x (github) for Space Station 14.",
I forgor to fix

2024-07-19 23:09 UTC, dvir001 commented on Resources/Prototypes/_NF/Events/events_nf.yml
> +    requireSafeAtmosphere: true
Low pop, let it be.

2024-07-19 23:12 UTC, dvir001 commented
Mc Fixing time

2024-07-20 09:52 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/Containers/box.yml
> +    - id: FoodCondimentPacketPepper
> random fruit (grapes, apple, pear, orange).

Healthy food-stuffs? In my McCargo meal?! I want my money back.

2024-07-20 10:05 UTC, ErhardSteinhauer approved these changes
Do be working

2024-07-20 16:42 UTC, whatston3 approved these changes
Set the max occurrences for the mccargocrate event to 4, should be generous enough for low-pop conditions.  Happy with this, should be a good feature. 😃

2024-07-20 16:55 UTC, merged