Medical paperwork templates
new-frontiers-14/frontier-station-14 pull request #1728
Opened 2024-07-24 16:29 UTC by ErhardSteinhauer

## About the PR
- Added 3 paper templates for medical doctors with forms for: patient record, prescription and health insurance.
- Mapped folder with new templates to Caduceus and Searchlight (also replaced pumps on Searchlight). 
- Added folder to Nanomed Plus along with gauze.

## Why / Balance
QoL

## How to test
1. Spawn `medical doctor folder`, examine papers inside.

## Media
![2024-7-24_19 24 20](https://github.com/user-attachments/assets/d1d87271-e620-4f12-8ecc-618690b7b6ab)
- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**
:cl: erhardsteinhauer
- add: Added a folder with paperwork templates for medical doctors to Searchlight and Caduceus and to Nanomed Plus.
- tweak: Added gauze to Nanomed Plus catalogue.

2024-07-24 16:32 UTC, dvir001 commented
Loadout option?

2024-07-24 16:33 UTC, ErhardSteinhauer commented
Would be nice, yeah. Sounds like a prime candidate for !!FUN!! category.

2024-07-24 19:59 UTC, whatston3 approved these changes
Looks alright, thanks for looking at the form changes.

2024-07-28 02:30 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Paper/forms_medical.yml
> +          [bold]Occupation:[/bold]
```suggestion
          [bold]Occupation:[/bold] 
          [bold]Vessel IFF:[/bold] 
```

Forgot about any associated ship you're interested in here, potentially useful in triage.

2024-07-30 12:12 UTC, dvir001 commented
We can probably add a new category called "docs" for RP and have people select from max one, so it wont effect the "Fun" options

2024-07-30 12:40 UTC, ErhardSteinhauer commented
> We can probably add a new category called "Docs" or something like this, for RP and have people select from max one, so it wont effect the "Fun" options

Maybe. But I believe paperwork is firmly on HRP territory. And I'm not sure if it's worth creating a full category for 3 items - SR folder, medical folder and nfsd folder (don't think there are any other player factions that require standardized paperwork, might be wrong here).

2024-07-30 12:41 UTC, ErhardSteinhauer commented
Probably can put folders with paperwork in `trinkets` category and increase the upper limit there.

2024-07-30 12:45 UTC, ErhardSteinhauer commented
Or! Or we can create a `Bureaucracy` category for all the stamps players want and drop folders with paperwork there.

2024-07-30 13:10 UTC, dvir001 commented
> Or! Or we can create a `Bureaucracy` category for all the stamps players want and drop folders with paperwork there.

Bureaucracy sound fine,

STC
SR
Medical
Nfsd
Etc

Let people just add stuff as it goes I think its fine to have this as a category.

For now you can yeet the medical one in it.

2024-07-30 18:58 UTC, whatston3 commented
> > Or! Or we can create a `Bureaucracy` category for all the stamps players want and drop folders with paperwork there.
> 
> Bureaucracy sound fine,
> 
> STC SR Medical Nfsd Etc
> 
> Let people just add stuff as it goes I think its fine to have this as a category.
> 
> For now you can yeet the medical one in it.

I've put up a set of changes for this loadout stuff here:

https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-07-Medcal-Forms...whatston3:frontier-station-14:2024-07-Medcal-Forms-suggestions?expand=1

Should probably be reviewed as a separate feature, but it includes squiggly signature sprites, stamps for doctors and engineers (for invoices/signoff RP), a bureaucracy loadout setup, and some cleanup better denoting NF stamps.

I think this branch as it is is good to go.

![image](https://github.com/user-attachments/assets/d4ed2818-fead-4241-aa52-422b50ed4bf5)

2024-07-30 19:06 UTC, ErhardSteinhauer commented
> > > Or! Or we can create a `Bureaucracy` category for all the stamps players want and drop folders with paperwork there.
> > 
> > 
> > Bureaucracy sound fine,
> > STC SR Medical Nfsd Etc
> > Let people just add stuff as it goes I think its fine to have this as a category.
> > For now you can yeet the medical one in it.
> 
> I've put up a set of changes for this loadout stuff here:
> 
> https://github.com/ErhardSteinhauer/frontier-station-14/compare/2024-07-Medcal-Forms...whatston3:frontier-station-14:2024-07-Medcal-Forms-suggestions?expand=1
> 
> Should probably be reviewed as a separate feature, but it includes squiggly signature sprites, stamps for doctors and engineers (for invoices/signoff RP), a bureaucracy loadout setup, and some cleanup better denoting NF stamps.
> 
> I think this branch as it is is good to go.
> 
> ![image](https://private-user-images.githubusercontent.com/166147148/353581685-d4ed2818-fead-4241-aa52-422b50ed4bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjYzODIsIm5iZiI6MTcyMjM2NjA4MiwicGF0aCI6Ii8xNjYxNDcxNDgvMzUzNTgxNjg1LWQ0ZWQyODE4LWZlYWQtNDI0MS1hYTUyLTQyMmI1MGVkNGJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxOTAxMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWRmNWM0NjYzYmIyNWUxNjk3ZTY2MzI2OWZhZjIzM2I0ZTk1MDcyZDdiODNjNmViZWMwNTc3YzlhMWFjZTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mugL7wMcBEmsCm8exP-Bq84LUiV_C2ulMRsBMwWTr2Y)

'Ery noice.

2024-07-30 20:56 UTC, whatston3 requested changes
Another review, another few requests.  Sorry.

2024-07-30 20:56 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Paper/forms_medical.yml
> +      - $XX XXX - Towing
```suggestion
      $XX XXX - Treatment
      $XX XXX - Revival
      $XX XXX - Cloning
      $XX XXX - Towing
```

The idea here is that these are additive (summing up your cost), but the coverage should be negative (covering all/part of your costs).  Is there a better way to do this?

```
       $XX XXX - Treatment
       $XX XXX - Revival
       $XX XXX - Cloning
       $XX XXX - Towing
      ($XX XXX) - Treatment Plan Coverage
      ($XX XXX) - Revival Plan Coverage
      ($XX XXX) - Cloning Plan Coverage
      ($XX XXX) - Towing Plan Coverage
```

2024-07-30 20:56 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Paper/forms_medical.yml
> +          [bold]$XXX XXX[/bold]
Might be annoying, but I think saying this is the total of the premium vs. the coverage (which could also be listed, but I don't think it's critical)
```suggestion
      [head=3]Total Premium[/head]
          [bold]$XX XXX[/bold]
```

2024-08-02 20:17 UTC, whatston3 approved these changes
It is good.

2024-08-03 19:08 UTC, whatston3 approved these changes
Think that should be it.  Recommending this to be merged.

2024-08-03 19:14 UTC, whatston3 commented
Erhard's signed off on this, gonna merge it.

2024-08-03 19:14 UTC, merged