Add currency notation
new-frontiers-14/frontier-station-14 pull request #1768
Opened 2024-08-02 16:23 UTC by GreaseMonk

## About the PR

This PR changes the display of spesos amounts from  $1000000  to  $1,000,000 (depending on the CultureInfo).

## Why / Balance

Makes it easier to discern

## How to test

Check the bank, vending machines, PDA, etc.

## Media

![image](https://github.com/user-attachments/assets/3899536c-d1d7-4e19-ad2d-a6272645524c)
![image](https://github.com/user-attachments/assets/5bc1aade-57d1-4bf1-aae2-ed610ccfebad)

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Currency notation

2024-08-02 16:30 UTC, arimah commented
No, you will not use `.` as a thousands separator in an English-language game, because `.` is the decimal separator in almost all English-speaking regions. You will use the locale-specific number format, such that it turns into `,` when the client is in English, ` ` when it's in Russian, and so on. And you will use the built-in locale formatting such that the Hindi server created five years from now uses correct placement of digit grouping for that region (`12,34,567.89` – yes, only the least significant group is three digits).

2024-08-02 16:39 UTC, arimah commented
You will also not hardcode the position of the currency symbol nor the currency symbol itself. In many parts of the world, the currency symbol comes _after_ the amount, ex. in Russian: `1 234 567,89 $`

2024-08-02 16:49 UTC, dvir001 commented
Like the PR but it needes the ``,``

And please add support to add prefix and suffix options that are not hardcoded

2024-08-03 18:12 UTC, whatston3 requested changes
The biggest issue I have with this is that some entries, in particular, YAML or FTL definitions for papers (see #1728) do not have a good way to inject this, so you have inconsistently localized oddities.

Apart from that, looks alright.  I've raised concerns where I have them in the code.  Will test and report back.

2024-08-03 18:12 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml
> +  name: spesos (5.000)
Consistency with en-US cultureinfo.
```suggestion
  name: spesos (5,000)
```

2024-08-03 18:12 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml
> +  name: spesos (10.000)
Consistency with en-US cultureinfo.
```suggestion
  name: spesos (10,000)
```

2024-08-03 18:12 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml
> +  name: spesos (20.000)
Consistency with en-US cultureinfo.
```suggestion
  name: spesos (20,000)
```

2024-08-03 18:12 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml
> +  name: spesos (40.000)
Consistency with en-US cultureinfo.
```suggestion
  name: spesos (40,000)
```

2024-08-03 18:12 UTC, whatston3 commented on Resources/Prototypes/_NF/Catalog/Fills/Items/briefcases.yml
> +  name: spesos (70.000)
Consistency with en-US cultureinfo.
```suggestion
  name: spesos (70,000)
```

2024-08-03 18:47 UTC, whatston3 commented
Testing seemed fine.

2024-08-03 20:39 UTC, whatston3 commented
Pushed a set of suggestions up onto 2024-08-03-balance-suggestions on my fork.

[Diff is available here (GitHub)](https://github.com/GreaseMonk/frontier-station-14/compare/balance...whatston3:frontier-station-14:2024-08-03-balance-suggestions?expand=1).

This allows the functions to be used for DB, uses $ specifically for spesos, and creates a set of convenience methods to get values in a particular currency, or to get a value independent of currency (function name for that one sucks, sorry).

I'd be happy to approve the branch with these changes in, and might suggest checking lines over for which are missing comments.

Here's a picture of these functions in use with the pirate uplink.

![doubloons](https://github.com/user-attachments/assets/434ed42f-2193-4121-820c-1f071c572fe2)

I don't really endorse this feature, seems like it touches many things for little gain, but with this, we can at least use it consistently.

2024-08-06 11:57 UTC, whatston3 approved these changes

2024-08-12 19:11 UTC, merged