Adds some spookuary cheer from Bing and Ghost Prince.
new-frontiers-14/frontier-station-14 pull request #2256
Opened 2024-10-16 03:58 UTC by dustylens

## About the PR

This adds two paintings produced by Bing and Ghost Prince in addition to several seasonal banners. They're a delight. I made none of these.

## Why / Balance

Spooktober

## How to test

Place things. Check rotations of banners.

## Media

![ss+(2024-10-15+at+07 51 45)](https://github.com/user-attachments/assets/f31058c6-ce65-4ba9-b0d8-5c93120269f9)

![ss+(2024-10-15+at+07 52 59)](https://github.com/user-attachments/assets/edbc403c-2af1-466e-864a-5a1b6ba8a79a)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
- add: Seasonal decorations. What fun.

2024-10-16 10:15 UTC, GreaseMonk requested changes

2024-10-16 10:15 UTC, GreaseMonk commented on Resources/Textures/_NF/Structures/Wallmounts/paintings_directional.rsi/meta.json
> +    "license": "CC-BY-SA-4.0",
There is some extra indentation here, best for it to stay the way it was

2024-10-16 10:15 UTC, GreaseMonk commented on Resources/Textures/_NF/Structures/Wallmounts/paintings.rsi/meta.json
> +    "license": "CC-BY-SA-4.0",
Some of these files had their license changed to 4.0 but then in Resources/Textures/_NF/Structures/Wallmounts/wall_hanging.rsi/meta.json  you added a new file with license 3.0

grrrr make up your mind :-)

2024-10-19 02:50 UTC, whatston3 approved these changes
Added construction graphs for streamers, made the entity names lowercase.

Licenses for paintings adjusted at Bing & GhostPrince's request.

Added a halloween-specific version of the random painting spawner (Thank you, Arimah, the holiday prototype swap code works wonders) and swapped it out for the regular random painting spawner on Halloween.

Added comments to the Frontier-specific HolidaySystem changes.

Looks alright to me, works fine under a modest amount of testing.  Another pair of eyes on this would be appreciated, but I think it's good to go.  Good stuff.

2024-10-19 13:11 UTC, GreaseMonk approved these changes
all good

2024-10-19 13:11 UTC, merged