Brigmedic Fix
new-frontiers-14/frontier-station-14 pull request #227
Opened 2023-08-18 19:00 UTC by dvir001

## About the PR
Missing a backpack, added it back and moved the starting list to the correct file.

2023-08-18 20:39 UTC, Cheackraze commented
Curious if this is what was causing the spawning bug

2023-08-18 20:45 UTC, dvir001 commented
> Curious if this is what was causing the spawning bug

It seem it was, the spawn was there, but the job was out.

2023-08-18 20:46 UTC, Cheackraze requested changes

2023-08-18 20:46 UTC, Cheackraze commented on Resources/Maps/Shuttles/helix.yml
> +#      type: Transform
Does the map loader allow commented entities? Regardless the game code will bulldoze that uid etc.  Better to just yeet and delete the map entry tbh

2023-08-18 20:46 UTC, Cheackraze commented on Resources/Maps/Shuttles/pulse.yml
> +#      type: Transform
Same here

2023-08-19 01:20 UTC, Cheackraze approved these changes

2023-08-19 01:20 UTC, merged