Trade Mall (Trade Outpost Alternate)
new-frontiers-14/frontier-station-14 pull request #2365
Opened 2024-11-03 20:34 UTC by Cheackraze

## About the PR

Adds an alternative trade outpost for some round variation. After lots of playtesting and feedback of the original outpost, this one aims to resolve some of the broader player feedback. Mostly of, it being too large and isolating of the areas, and while having lots of blank space to make player spaces is a sound idea, only the large abandoned atrium ever really got used.

Big thanks to mariusdemeier and trucy_deuxy for initial layout and design work.

TODO:
[ ] add cameras
[ ] modify kitchen dock (it needs 3 more tiles of clearance to fit a bocadillo)
[ ] power pass, make sure everything is properly powered (kitchen and atm area had issues)
## Why / Balance

Variety/Feedback
## How to test

Load up a normal (non-debug) round of frontier. There will be a 50/50 chance of it spawning. You may have to `restartroundnow` a few times if it doesnt roll right.
## Media

TBA
## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [ ] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

:cl:
- add: Added the Trade Mall, an alternate to the Trade Outpost.

2024-11-03 23:52 UTC, PeccNeck commented
I've already voiced this once in the Discord forum post, but I'm very iffy about having separate areas for guard and NFSD. They've definitely been nicely decorated, but it ends up feeling redundant to me (NFSD especially, who have their entire POI). They also both share the same basic access, too (Security), so there's nothing stopping the Guard from waltzing over to NFSD and vice versa.

Semi-related, sad to see the NFSD intercom in the Guard section didn't make the cut, as they have no direct channels to NFSD otherwise, but at least there's one in the office on the other side of the hall.

2024-11-03 23:56 UTC, Cheackraze commented
this office is actually intended as a shared nfsd/sec guard post, to be manned by either. I mainly just wanted to give them both their own secured docking access, as the reasoning behind the 'split'. Overall i concurr

![image](https://github.com/user-attachments/assets/02ac0927-63c6-4194-9c3d-4f31e69a27bc)


> I've already voiced this once in the Discord forum post, but I'm very iffy about having separate areas for guard and NFSD. They've definitely been nicely decorated, but it ends up feeling redundant to me (NFSD especially, who have their entire POI). They also both share the same basic access, too (Security), so there's nothing stopping the Guard from waltzing over to NFSD and vice versa.
> 
> Semi-related, sad to see the NFSD intercom in the Guard section didn't make the cut, as they have no direct channels to NFSD otherwise, but at least there's one in the office on the other side of the hall.
> 
> And completely separately, I've just noticed that the decals for Cargo Bay 3 overlap the dark tiles on one side and are overlapped by them on the other.

The cargo bay area is mostly untouched from the original designer, but I can go in and alter the decals when I make my final pass

2024-11-04 00:21 UTC, blackknight954 commented
So overall this just looks like a revamped trade outpost? Why the 1/2 chance to spawn one or the other?

2024-11-04 00:33 UTC, Cheackraze commented
> So overall this just looks like a revamped trade outpost? Why the 1/2 chance to spawn one or the other?

for variety? why not?

2024-11-04 00:40 UTC, blackknight954 commented
> > So overall this just looks like a revamped trade outpost? Why the 1/2 chance to spawn one or the other?
> 
> for variety? why not?

Yeah I guess, but I'm imagining that trade outpost is just gonna remain a ghost town whereas the mall is gonna get all the action, but we'll see.

2024-11-04 01:06 UTC, Cheackraze commented
> > > So overall this just looks like a revamped trade outpost? Why the 1/2 chance to spawn one or the other?
> > 
> > 
> > for variety? why not?
> 
> Yeah I guess, but I'm imagining that trade outpost is just gonna remain a ghost town whereas the mall is gonna get all the action, but we'll see.

my intent with the closed up shops is to be more heavy-handed doing the same thing the original is trying to do. So, players making shops and populating it a bit more might carry over to the original trade outpost, which is set up for the same kind of thing but just is a little lighter in its suggestions for it

2024-11-04 02:13 UTC, Houtblokje commented
Overall, looks pretty good, I definitely like the shape and most of the layout. Especially the cargo area looks pretty cool, since you can easily reach and interact with the other cargo rooms, which I think was one of the big issues with the current trade station. 

but I had a few questions about this new layout. Mainly:
I see the mail office and the janitorial office here. Does this mean those facilities will be removed from Frontier outpost? Will their jobs be located on Trade? if so, is there a console to re-open the slots?
If this station is going to have a little medical area, maybe it could also get a cryo area, to take the pressure off frontier outpost during the end of game rush and to lure people more to it?

Not sure how I feel about the big open area, it often goes unused since nobody knows its allowed to be modified and what modifications are allowed, but I guess it is nice to have a big space to do fun stuff in.

The STC room could do with a water cooler.

2024-11-04 02:17 UTC, Cerebral-Error commented
> Overall, looks pretty good, I definitely like the shape and most of the layout. Especially the cargo area looks pretty cool, since you can easily reach and interact with the other cargo rooms, which I think was one of the big issues with the current trade station.
> 
> but I had a few questions about this new layout. Mainly: I see the mail office and the janitorial office here. Does this mean those facilities will be removed from Frontier outpost? Will their jobs be located on Trade? if so, is there a console to re-open the slots? If this station is going to have a little medical area, maybe it could also get a cryo area, to take the pressure off frontier outpost during the end of game rush and to lure people more to it?
> 
> Not sure how I feel about the big open area, it often goes unused since nobody knows its allowed to be modified and what modifications are allowed, but I guess it is nice to have a big space to do fun stuff in.
> 
> The STC room could do with a water cooler.

There does look like there's a small Cryo area up near the North end of the station, right next to the toilets. There's a pair of cryo chambers.

2024-11-04 02:19 UTC, Houtblokje commented
> > Overall, looks pretty good, I definitely like the shape and most of the layout. Especially the cargo area looks pretty cool, since you can easily reach and interact with the other cargo rooms, which I think was one of the big issues with the current trade station.
> > but I had a few questions about this new layout. Mainly: I see the mail office and the janitorial office here. Does this mean those facilities will be removed from Frontier outpost? Will their jobs be located on Trade? if so, is there a console to re-open the slots? If this station is going to have a little medical area, maybe it could also get a cryo area, to take the pressure off frontier outpost during the end of game rush and to lure people more to it?
> > Not sure how I feel about the big open area, it often goes unused since nobody knows its allowed to be modified and what modifications are allowed, but I guess it is nice to have a big space to do fun stuff in.
> > The STC room could do with a water cooler.
> 
> There does look like there's a small Cryo area up near the North end of the station, right next to the toilets. There's a pair of cryo chambers.

Ah I see it. I expected it near medical however, so maybe something similar can be created instead of the toilets across from medical?

2024-11-04 02:23 UTC, Cheackraze commented
> > > Overall, looks pretty good, I definitely like the shape and most of the layout. Especially the cargo area looks pretty cool, since you can easily reach and interact with the other cargo rooms, which I think was one of the big issues with the current trade station.
> > > but I had a few questions about this new layout. Mainly: I see the mail office and the janitorial office here. Does this mean those facilities will be removed from Frontier outpost? Will their jobs be located on Trade? if so, is there a console to re-open the slots? If this station is going to have a little medical area, maybe it could also get a cryo area, to take the pressure off frontier outpost during the end of game rush and to lure people more to it?
> > > Not sure how I feel about the big open area, it often goes unused since nobody knows its allowed to be modified and what modifications are allowed, but I guess it is nice to have a big space to do fun stuff in.
> > > The STC room could do with a water cooler.
> > 
> > 
> > There does look like there's a small Cryo area up near the North end of the station, right next to the toilets. There's a pair of cryo chambers.
> 
> Ah I see it. I expected it near medical however, so maybe something similar can be created instead of the toilets across from medical?

the intent is to make people walk through the station to get to it. Same with having the ATM/shipyard console on the opposite end of the Cargo console. It may 'feel like a pain in the ass' but the intent is that you should walk all through the station with the goal of players having chance interactions in the hallways etc.

As for the janitor/mail, we dont plan on removing them from frontier outpost, its more just another space that they can choose to use instead.

2024-11-04 03:05 UTC, Houtblokje commented
> the intent is to make people walk through the station to get to it. Same with having the ATM/shipyard console on the opposite end of the Cargo console. It may 'feel like a pain in the ass' but the intent is that you should walk all through the station with the goal of players having chance interactions in the hallways etc.
> 
> As for the janitor/mail, we dont plan on removing them from frontier outpost, its more just another space that they can choose to use instead.

Not sure what roleplay opporunities you see in delaying people who are actively trying to not play the game anymore, but sure I guess? I do get the other stuff though.

2024-11-05 23:47 UTC, PeccNeck commented
Went ahead and submitted some bits and tweaks on #2373, take a look when you can.

2024-11-10 12:19 UTC, dvir001 commented
Fixed warp point and metadata.

2024-11-19 23:23 UTC, Cheackraze commented
this is all good to go now. I cant get an updated map render because my maprenderer breaks on "entity uid 0" internal exception. No substantial changes from the above images, besides a slightly modified kitchen dock and added cameras.

2024-11-20 06:38 UTC, arimah commented
Failures come from these lines:

https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L24873-L24875
https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L25349-L25351

tl;dr: don't use a network configurator or multitool's overlay. :D These will have to be edited out manually.

I will give this a proper review in the coming days.

2024-11-20 06:45 UTC, arimah commented
I will say this right away, actually: the Christmas trees _have to_ go until we've fixed the present pool. It's _way_ too easy to get gifts that are dangerous or game-breaking in some way.

2024-11-20 10:24 UTC, dvir001 commented
Fixed the yml, I hope.

2024-11-20 11:23 UTC, arimah commented
@dvir001 You don't have to remove `parent: invalid` getting the grid's Transform component. The map deserialiser explicitly ignores that one case, and it'll just be reintroduced whether the map is edited anyway. :>

2024-11-20 15:46 UTC, arimah commented
> I'm not convinced your reasoning is correct here. My latest updates changed exactly 0 network devices and i hadn't used any kind of network config tool for this.

🤔 You're right, it's actually not the overlay that causes `configurators` to be set. Merely adding a device to a multitool or network config is enough to put it in this list. TIL!

2024-11-20 15:54 UTC, Cheackraze commented
> I will say this right away, actually: the Christmas trees _have to_ go until we've fixed the present pool. It's _way_ too easy to get gifts that are dangerous or game-breaking in some way.

The gift pool has literally nothing dangerous in it, it was removed by wizden last Christmas after they kept giving out thronglers on it. If anything, you can lower the chance for the 'insane' version, but this is kinda the whole meaning and draw of the Christmas gifts

2024-11-20 16:05 UTC, arimah commented
> The gift pool has literally nothing dangerous in it, it was removed by wizden last Christmas after they kept giving out thronglers on it.

Just a few weeks ago, Wookie spawned a gift-giving Christmas tree that someone got a Syndicate monkey box from. It made a space bear on FO. Feel free to check the ahelp relay. In my own testing, I've managed to unwrap a syndicate footsoldier, a holoparasite, a Syndicate hardbomb, an anomaly, and more. Whatever is supposed to have been removed, I don't know, but the insane gifts are still, well, insane.

2024-11-20 20:26 UTC, PeccNeck commented
> Failures come from these lines:
> 
> https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L24873-L24875
> 
> https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L25349-L25351
> 
> tl;dr: don't use a network configurator or multitool's overlay. :D These will have to be edited out manually.

Oops... Those were me. Didn't know! Is there a better way to link devices for any future mapping I do, or should I just be more vigilant and edit these out in post?

2024-11-20 20:36 UTC, Cheackraze commented
its gotta be something specific because I linked the entire outpost up to air alarms, fire locks, shutters, the whole shebang and it didnt fail like this

> > Failures come from these lines:
> > https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L24873-L24875
> > 
> > https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L25349-L25351
> > 
> > tl;dr: don't use a network configurator or multitool's overlay. :D These will have to be edited out manually.
> 
> Oops... Those were me. Didn't know! Is there a better way to link devices for any future mapping I do, or should I just be more vigilant and edit these out in post?

2024-11-20 21:21 UTC, PeccNeck commented
> its gotta be something specific because I linked the entire outpost up to air alarms, fire locks, shutters, the whole shebang and it didnt fail like this
> 
> > > Failures come from these lines:
> > > https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L24873-L24875
> > > 
> > > https://github.com/new-frontiers-14/frontier-station-14/blob/ea05405aefeb479a61a88c7f7aa55905f916d1ab/Resources/Maps/_NF/POI/trademall.yml#L25349-L25351
> > > 
> > > tl;dr: don't use a network configurator or multitool's overlay. :D These will have to be edited out manually.
> > 
> > 
> > Oops... Those were me. Didn't know! Is there a better way to link devices for any future mapping I do, or should I just be more vigilant and edit these out in post?

Huh. Definitely odd... Maybe it is the overlay after all? I do tend to use that just to be sure I haven't missed anything (and sometimes I have).

Either way, those lines are definitely from my PR according to the git blame; clearly I did something wrong, just a matter of figuring out what. Had this happen to me with other grids I've saved as well, so whatever it is I'm doing, I'm doing it consistently.

2024-11-21 21:46 UTC, arimah requested changes
Overall, I like it. It has a very unique shape and looks good in many, many ways. We've discussed a few of the larger initiatives in VC, none of which are blockers for getting this merged. The following is therefore largely a list of nitpicks. :)

![image](https://github.com/user-attachments/assets/3f70ae98-b02f-44b2-aa2b-1494f7940010)
This corner is dark. Suggested new light placement:
![image](https://github.com/user-attachments/assets/884fc4a8-a5f5-4d74-88b4-1beb8f31fe22)

The corridor outside also feels a touch underlit compared to the rest:
![image](https://github.com/user-attachments/assets/f0c0674a-1f85-4515-8a07-17918e9ae8d3)

![image](https://github.com/user-attachments/assets/17c18b48-6861-42a5-b7d8-7d96b56c13fd)
Another dark place. I suggest putting a light in the middle of that wall, symmetric with the shop opposite.

![image](https://github.com/user-attachments/assets/050658e1-bfa2-4d59-81ac-4bb053d6f383)
The only food vendor in the entire system, wow! ... I'm not sure we should have it there. :)

![image](https://github.com/user-attachments/assets/9b56acc9-86e6-4d39-bbb3-1e1c9b95074c)
North bus dock is also pretty dark. Not a huge deal.

![image](https://github.com/user-attachments/assets/73535e11-9c02-4b13-92cc-d49d4150ea8b)
As per our discussion in VC, replace the ChefVend with a sink and replace the range with a deep fryer.

![image](https://github.com/user-attachments/assets/20cff0e6-b7e7-4416-978a-2e2871ac8474)
The windoors here are almost invisible. Suggest removing them, it's just a kitchen counter. :)

![image](https://github.com/user-attachments/assets/842c4d2a-a172-45f1-bab9-626f007f7c1c)
This station map has no power cell. Swap it for the `[Powered]` version.

![image](https://github.com/user-attachments/assets/d8fb7aa6-d597-4336-ac2c-645c9dedcc36)
This station map too.
Also, catwalk under the generators would make it instantly obvious that there's HV power cable.

![image](https://github.com/user-attachments/assets/4ced69c2-9e0f-45a2-8600-17f364434d87)
Left-hand conveyor belt needs to be turned 180° – it moves in the opposite direction to the other two. :) Also the recycler and mat reclaimer do the same thing now, we can skip one of them.

And lastly, I think it could do with a few dirt decals. All the dirty spessmen feet tracking mud everywhere must surely give the janitor something to clean!

2024-11-26 18:27 UTC, Cheackraze commented
all concerns listed addressed, this should be good to merge!

2024-11-26 19:33 UTC, whatston3 commented
A dock numbering scheme might be handy.  Thoughts on the one below?  Similar to the Trade Outpost names:

![image](https://github.com/user-attachments/assets/7165cc0d-f80d-41ab-8e7d-5d2eb2d7a426)

2024-11-26 19:35 UTC, Cheackraze commented
looks fine to me, the only reason I havent been labeling the docks is localization issues but that would work fine if you want to commit or make changes

2024-11-26 19:43 UTC, dvir001 commented
> looks fine to me, the only reason I havent been labeling the docks is localization issues but that would work fine if you want to commit or make changes

They actually should support FTL format if you use FTL in the name as far as I know, I might have to retest.

2024-11-26 19:45 UTC, whatston3 commented
> > looks fine to me, the only reason I havent been labeling the docks is localization issues but that would work fine if you want to commit or make changes
> 
> They actually should support FTL format if you use FTL in the name as far as I know, I might have to retest.

They don't right now, I got lazy, but it's an easy addition.  One sec.

2024-11-26 20:33 UTC, dvir001 commented on Resources/Prototypes/_NF/PointsOfInterest/trademall.yml
> +  busStop: true
Note some of the changes on this yml are not in the comp anymore, need to update

2024-11-26 20:50 UTC, whatston3 commented
> looks fine to me, the only reason I havent been labeling the docks is localization issues but that would work fine if you want to commit or make changes

https://github.com/new-frontiers-14/frontier-station-14/pull/2467
boop

2024-11-26 21:42 UTC, whatston3 commented
> are both ready to go? or do we need to now update all the dock labels too again

Whichever one merges first, the other should be updated.

Also, fixed up the trade mall prototype re: dvir's comments (should've done that earlier, my bad).

2024-11-26 22:09 UTC, whatston3 commented
Dusty's requested changes are up here - three airlocks per cargo dock (all labelled), swaps the position of the shelf and westmost light in the kitchen: https://github.com/new-frontiers-14/frontier-station-14/commit/26e8eef6bc767c24ea524f512ca139c3364024b2

All of the new cargo airlocks should have techmaint floors underneath them with the same warning decals as the existing ones.

Cargo bay 3, three red airlocks and docking airlocks.
![image](https://github.com/user-attachments/assets/204b2b4c-5755-4fc7-a343-617fe6673690)

Kitchen, note the swapped shelf and wall-mounted light.
![image](https://github.com/user-attachments/assets/95b82f24-3640-4bf1-a11e-67b645e0ee1b)

2024-11-27 08:41 UTC, arimah approved these changes
![image](https://github.com/user-attachments/assets/fce02f0d-7ffd-4c0f-8a31-63d23cacd2b2)

2024-11-27 08:41 UTC, merged