Ramen dishes and soy bottle.
new-frontiers-14/frontier-station-14 pull request #2615
Opened 2024-12-26 18:57 UTC by dustylens

## About the PR

This PR adds 
- Six ramen dishes with recipes and sprites created by our own @wallflowerghost / Umami, (sometimes the SR). I simply did the knuckle dragger work of yml shoveling. 
- A new fancy soy sauce bottle with a little sprite tinkering by myself. 
- Some new flavors to stimulate the mind.

## Why / Balance

More food = good.

## How to test

Double check the food tags, nutriment stuff and all of that. I still have no idea what the new nutrition stuff is supposed to be someday and I don't wanna undermine any guidelines that may emerge in the future.

Cook the food. Buy the sauce. 

A to-do is adjust bowl recipes to allow for seasoning. Need to hammer that out. Someday.

## Media

![ss+(2024-12-26+at+10 45 00)](https://github.com/user-attachments/assets/0881e1a9-f0c0-4371-b1e2-a66fd713f561)

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes

**Changelog**

🆑 
- add: New ramen dishes from Umami! (Sometimes the SR)

2024-12-26 19:00 UTC, wallflowerghost commented
LOOK MA, I MADE SPRITE ART AND RECIPES! I DID IT! 😀

2024-12-28 00:39 UTC, wallflowerghost requested changes
I've literally never used Github like this before, so I think trying to do this is funny ;P

2024-12-28 00:39 UTC, wallflowerghost commented on Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meals.yml
> +  description:
Missing the description: "Miso, or fermented bean paste, broth with scallion and egg. Robust!" (I think? Am I doing this right, ma?)

2024-12-28 00:39 UTC, wallflowerghost commented on Resources/Prototypes/_NF/Entities/Objects/Consumable/Food/meals.yml
> +  description: Sea salt broth with corn and seaweed.
Missing the little "Light!" at the end (the full description being "Sea salt broth with corn and seaweed. Light!")

2025-01-09 21:53 UTC, Cerebral-Error commented
Late to the party on this one, but _yessss._

2025-01-10 21:47 UTC, GreaseMonk approved these changes

2025-01-10 21:48 UTC, merged