adds a nightclub POI (Club Singulo)
new-frontiers-14/frontier-station-14 pull request #2638
Opened 2024-12-30 20:29 UTC by emrekmek

## About the PR
Adds a new Nightclub POI called "Club Singulo"

## Why / Balance
A new POI to spawn instead of Tinnia's or Bahama Mama's because more is better :P
(This PR in this form only adds the .yml of the POI since I don't quite know how to add it to the roster, I'd appreciate a maintainer/maptainer looking over that)

## How to test
Download the .yml and loadgrip it into space

## Media
![2024-12-30_23 17 32](https://github.com/user-attachments/assets/157f547c-fffb-425a-842d-3e9712e6af27)
UNINITIALIZED + Subfloor
Dancefloor, Bar, Seating Area

![2024-12-30_23 17 38](https://github.com/user-attachments/assets/8b7432c2-ddab-44a5-94c5-f9beac7c74da)
UNINITIALIZED + Subfloor
Kitchen, Hydro, Main Hallway, Bathrooms, Maints

![2024-12-30_23 17 52](https://github.com/user-attachments/assets/26f46a52-bf18-405a-be98-78eb139e7818)
UNINITIALIZED + Subfloor
Docking Arm, Solars

![2024-12-30_23 22 01](https://github.com/user-attachments/assets/05fafebc-aa77-478a-935f-a0ea3a0ccfe9)
INITIALIZED
Dancefloor, Bar, Seating Area

![2024-12-30_23 22 05](https://github.com/user-attachments/assets/b8e447e0-5297-4554-b727-463880db914a)
INITIALIZED
Kitchen, Hydro, Main Hallway, Bathrooms, Maints

![2024-12-30_23 22 11](https://github.com/user-attachments/assets/682c7473-830c-42ea-9cca-1b5353f3c90d)
INITIALIZED
Docking Arm, Solars

![massscanner](https://github.com/user-attachments/assets/dfd25eb3-0103-4ec2-903b-f0c53ad20db5)
Mass scanner view

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
I hope nothing!

**Changelog**

:cl:
- add: Nightclub POI (Club Singulo)
-->

2025-01-12 13:35 UTC, Cheackraze commented
A quick review just off from the images:

Doors inset diagonally like this should be avoided whenever possible, it makes interactions feel bad when moving around this corner
![image](https://github.com/user-attachments/assets/9e09037b-d5f9-43d3-a2e9-8135a9e53f91)

long stretches of windows like this are uninteresting to look at, and provide no cover/hiding through windows. These are perfect places for some 'support' 'pillars' to block view partially, maybe to put a custom bar sign on or something
![image](https://github.com/user-attachments/assets/41a030c0-53e6-41e4-b1b8-9f00f5214880)

no condiment station? if its supposed to be inside our 'restaurant' POI spawning pool, it should be full service to match tinnia/bahamma in at least the player QOL aspects
![image](https://github.com/user-attachments/assets/257451c6-e948-4ec3-a006-b379817ddeba)

only 2 interior docks is too few, especially for a POI that will be on the public transit route. Consider adding at least 1, preferably 2 more life-supported docks (my suggestion for location in the picture).  Also, be sure that the POI is included in both the public transit system and the smuggling drops system. 
![image](https://github.com/user-attachments/assets/4a446029-927f-4754-8a3e-9bca0315759d)

and also, you should include a 'sell only' shipyard console here as well, especially given the limited docking space, and the fact that some people prefer ending their shifts on the restaurant POIs.

Overall, I like the idea behind it and its got a good start. A few design changes I pointed out, and then once those are made I can load it up and do some more fine-tooth reviewing. Its also quite open space throughout, so make sure its well fire-locked to prevent any catastrophic atmos failures.

2025-01-12 13:36 UTC, Cheackraze requested changes
Minor design changes

2025-01-12 13:46 UTC, emrekmek commented
@Cheackraze 

Sounds doable :P Once I got some more time on my hands I'll look to implementing them :)

Also some other things to add/change:
Mass Scanner Console
Adequate Atmos Setup
Bigger Maints MAYBE
ATM
Freezer into the Freezer room

2025-03-11 19:55 UTC, dvir001 commented
Temp closed by author request

2025-03-11 19:55 UTC, closed without merging