Mercfab recipes
new-frontiers-14/frontier-station-14 pull request #2639
Opened 2024-12-30 23:38 UTC by blackknight954

## About the PR
Allows the mercfab to print Arsenal equipment, and have rubber ammo boxes upon unpacking it.
## Why / Balance
With the exception of ship guns, more specifically the grenade launchers, most Arsenal tech does not have enough destructive power in space to warrant gating it to only NFSD.

## How to test

Load a server
Spawn a Mercfab, observe the rubber rounds
Do some arsenal research, observe the arsenal tech added to the fab.

## Media
Rubber rounds
![image](https://github.com/user-attachments/assets/7d1eae1e-d5b1-47eb-982b-9dc98b38faa6)
Incendiary and uraniuum munitions
![image](https://github.com/user-attachments/assets/eaf78151-5cd2-4d2f-b399-122cd084f1b9)

## Requirements
- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an ingame showcase.

## Breaking changes
Nothing I can see.
**Changelog**
:cl:
- The Mercfab is able to print arsenal technology, excluding ship guns and grenade launcher shells.

2024-12-30 23:40 UTC, dvir001 commented
Uranium and Incendiary ammo are power creep used in upsteam to fight nukies, I will avoid giving them in printing as they break balance for AI and PVP / PVE

2024-12-31 00:23 UTC, blackknight954 commented
> Tranquilizer is busted still

Is it? I've tested shooting 4 shells at NPC's and they yawn but they don't sleep in most cases

2025-01-10 22:01 UTC, GreaseMonk requested changes
Restart the PR on a new branch having only 1 commit and one file change preferably,  currently it says 20 commits 1 file change. if this isn't a github screw-up, something is not right with this PR.

![image](https://github.com/user-attachments/assets/73aa15ee-8179-4f2a-b4a8-074a6c57adde)

2025-01-11 04:33 UTC, closed without merging

2025-01-11 05:31 UTC, blackknight954 commented
@GreaseMonk 

Sorry for the delay

New PR can be found here:
https://github.com/new-frontiers-14/frontier-station-14/pull/2677