Taco tuesday
new-frontiers-14/frontier-station-14 pull request #266
Opened 2023-08-24 22:28 UTC by pabloichiban

Adds Tacos and other Tex-Mex treats to the game.  Now in the proper _NF folder!

Adds: 9 Tex-Mex themed goodies and recipes to the game
**https://docs.google.com/document/d/1gPYtbeQ7NeD6jb5VVKDMslYvb7opGRJsAEQ2yK_-nzc/edit?usp=sharing**

2023-08-26 02:07 UTC, Cheackraze requested changes

2023-08-26 02:07 UTC, Cheackraze commented on Resources/Prototypes/Recipes/Cooking/meal_recipes.yml
> +    FoodChili: 2
you forgot to delete all this in the file

2023-08-26 02:07 UTC, Cheackraze commented on Resources/Prototypes/_NF/Recipes/Cooking/meal_recipes.yml
> +
looks like you forgot to delete everything above here in this file when you did your copy + paste

2023-08-26 02:07 UTC, Cheackraze commented on Resources/Prototypes/_NF/Recipes/Cooking/meal_recipes.yml
> +    FoodChili: 2
this recipe is a large meal and has funny properties, should make it require some additional unique ingredient to craft

2023-08-27 11:24 UTC, potato1234x commented
why not add these to the base game

2023-09-19 16:54 UTC, Cheackraze commented
Im gunna finish this PR this week and get them in, though I would like to get the WIKI up first so we can list the recipes

2023-12-01 17:53 UTC, closed without merging