Arcadia drip
new-frontiers-14/frontier-station-14 pull request #341
Opened 2023-09-20 23:18 UTC by AjexRose

## About the PR

Added clothing for the faction of Arcadia Industries. and In the future will also add a Vendor for them that can be obtained via expedition loot. 

## Why / Balance

During the townhall, there were mentions of inserting more player made factions into the frontier, so I thought this would be a good start. 

**Changelog**

added: Arcadia Industries is now beginning marketing in the frontier with unique clothing items, unlockable by those with combat prowess.

2023-09-21 19:03 UTC, Cheackraze commented
love it.  My only issue is, we need to keep all of our entities separated from the base game files. So for all of your yml entries, we need new files created inside /prototypes/_NF/ instead of adding to the vanilla ones.

This is so that maintainers (just me for now) have a much, *MUCH* easier time when it comes to bringing in changes from vanilla SS14 so that the files do not conflict.  Once we get everything split into their own files, we can get this in and start making a POI for you guys!

2023-09-21 19:06 UTC, AjexRose commented
Alrighty, I'll try to get all the files to the _NF section of the code!

2023-09-22 20:16 UTC, AjexRose commented
@Cheackraze The Arcadia Clothing hopefully all fully within the _NF folders now.

2023-09-27 04:58 UTC, Cheackraze requested changes

2023-09-27 04:58 UTC, Cheackraze commented on Resources/Prototypes/_NF/Entities/Clothing/Belt/belts.yml
> +  capacity: 60
yml is sensitive to indentation, so everything under the `  components:` needs to get formatted with 1 more double space indent

2023-09-28 20:58 UTC, Cheackraze commented on Resources/Prototypes/_NF/Entities/Clothing/Masks/masks.yml
> +    sprite: _NF/Clothing/Mask/arcadia-battleface.rsi
typo. should be /Masks/ ill fix it so we can merge it

2023-09-28 20:59 UTC, Cheackraze approved these changes

2023-09-28 21:38 UTC, merged