Port carrying from Delta-v
new-frontiers-14/frontier-station-14 pull request #501
Opened 2023-10-28 00:03 UTC by Leander-0

## About the PR
Adds the carrying system and gives the component to all available species. Carry the dead, carry the wounded, carry the people you want to throw, carry the prisoners, carry the felinids and launch them at mach 5 to the void of space where they belong when they spam meows.

## Why / Balance
Can be used by pirates to throw mates for boarding, sec for carrying prisoners, medics for carrying the wounded or just to throw away some people to space.

## Technical details

Most of the carrying code is already in this repository, this just takes the changes done on delta with some little changes so it could build, "it works on my machine" right now.

## Media

https://github.com/new-frontiers-14/frontier-station-14/assets/80334192/20c8f86e-5eac-48df-91f7-01a24eb376b4

- [x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl: Leander
- add: All species have learned how to carry people and throw them around.

2023-10-28 03:16 UTC, GrandKadoer commented
This is absolutely crucial for EVA rescue operations imo.

2023-10-29 17:15 UTC, Cheackraze requested changes

2023-10-29 17:15 UTC, Cheackraze commented on Content.Server/Resist/EscapeInventorySystem.cs
> +        if (TryComp<BeingCarriedComponent>(uid, out carried))
youve doubled up this guard clause, we only need one. Preferably the better commented one lol

2023-10-29 17:15 UTC, Cheackraze commented on Content.Shared/Nyanotrasen/Carrying/CarryingSlowdownComponent.cs
> +    public sealed class CarryingSlowdownComponentState : ComponentState
components all need to be partial or they will explode

2023-10-29 20:58 UTC, Leander-0 commented
Issues should be fixed

2023-10-29 22:52 UTC, Cheackraze approved these changes

2023-10-29 22:53 UTC, merged