Decade Dove
new-frontiers-14/frontier-station-14 pull request #503
Opened 2023-10-28 10:55 UTC by crystalHex

## About the PR
Added the Decade Dove - an expedition-capable shuttle with a salvage and robotics bay.

## Media

Without lighting, including spawns:
![spawns](https://github.com/new-frontiers-14/frontier-station-14/assets/148453998/a60b7e76-0c26-44c2-946f-74adb4e424c5)
With lighting:
![lighting](https://github.com/new-frontiers-14/frontier-station-14/assets/148453998/5feb4ed3-5fb8-4ac6-8f87-f9316765c750)
Bridge:
![bridge](https://github.com/new-frontiers-14/frontier-station-14/assets/148453998/8e4ba361-3f83-4a86-bd4b-997d160cf09e)
Front section:
![front](https://github.com/new-frontiers-14/frontier-station-14/assets/148453998/d6dd24d6-1a38-44eb-a9f5-4051a5b6a713)
Back section:
![back](https://github.com/new-frontiers-14/frontier-station-14/assets/148453998/8bf88017-ec99-4d74-9ed3-bd30c5d53d77)

- [ x] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

2023-10-29 17:21 UTC, Cheackraze commented
overall Id say this one is a bit borderline on-the-nose but I suppose I'll allow it.  My biggest critique is that its overly lit.  Each of your small rooms should only need at most 1 light source, and some have up to 8. Intense lighting like that washes out our lighting engine, removes contrast and overall makes things look really flat.  And in some scenes it could cause rendering artifacts if there are too many lights trying to be rendered at once.

Overall sound design (ignoring the obvious reference) and really good decoration work. While I am seeing a distinct lack of decals, your rooms and corridors are small and cluttered enough to mitigate it and it doesnt look empty like most un-decal ships look.

Take out half or more of the lights and this one will be good to go to add to the expedition lodge.

2023-10-31 12:06 UTC, crystalHex commented
So I removed most of the lights and the ship is looking a bit better now.

2023-11-02 23:16 UTC, Cheackraze commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/71046427/cfe1287e-e6ca-489b-9348-3dd121cbc133)
these windows have shuttle walls overtop of them so you cant see out

2023-11-02 23:19 UTC, Cheackraze requested changes

2023-11-02 23:19 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/decadedove.yml
> +  group: Civilian
This needs to be a part of the Expedition group, since it is an Exped vessel

2023-11-02 23:19 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/decadedove.yml
> +  name: NT Decade Dove
I think the name is too on-the-nose. Maybe just the 'Dove' or similar, or some unrelated name. The silhouette and design still clearly indicates the reference, we dont need to be that heavy handed.

2023-11-02 23:19 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/decadedove.yml
> +            ChiefEngineer: [ 0, 0 ]
should be regular station engineers. The head roles should be more for ships that are larger or for ships that are hyper-specialized.

2023-11-02 23:28 UTC, Cheackraze commented
the ship itself is well done, just some minor other changes and we can get this in!

2023-11-03 12:40 UTC, crystalHex commented
Should the NT part of the name be changed for a manufacturer prefix as well?

2023-11-06 22:09 UTC, crystalHex commented
Alright, I finally made the requested changes. I also went ahead and changed the look of the ship by a bit.

2023-11-09 03:43 UTC, Cheackraze approved these changes

2023-11-09 03:44 UTC, merged