Making some slight updates and fixes to the Comet
new-frontiers-14/frontier-station-14 pull request #517
Opened 2023-10-31 10:34 UTC by Shodhans

## About the PR

This PR covers some very minor changes to the Comet, nothing major or groundbreaking, just a few things that got missed on release.

## Why / Balance

Some things are just minor QOL changes, others were issues pointed out to me by people who had flown the Comet themselves and come to the conclusion a few things could be changed/fixed/added. I don't believe any of these changes substantially change the way it operates or the benefits that it gives.
## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

https://youtu.be/qhkFQC1FbO0

## Breaking changes

**Changelog**

- tweak: Turned on one of the west-facing thrusters that was accidentally toggled 'off' by default
- tweak: Shut the captain's locker that had been left open by default
- add: Added a pair of insuls and engineering goggles to the CE locker that had been intended to be in there, but was forgotten
- tweak: Moved the bridge's 'panic button' from its location on the window slightly further back, as people were able to press the panic button from either side in its original place
- add: Added shutters covering the windows to the bridge that are linked to the panic button, as it was pointed out that locking yourself in a room with only windows might not be a good idea if the enemy has lasers. Airlocks do not have shutters over them.
- tweak: The AME shielding pieces were oriented incorrectly; this has been fixed.

2023-10-31 15:47 UTC, FoxxoTrystan requested changes
Your changlog is extremly confusing.

A reminder that the changlog will not mention your PR/Ship.
I recomend to change your changelog to one line or mention the Comet ship.

Example:
- tweak: Comet Ship recived some maintenance.

or:
- fix: Comet Ship AME is now in the correct rotation.
- tweak: Comet Ship panic button location has changed.
ect...

2023-10-31 17:07 UTC, Shodhans commented
Will do, apologies for the confusion!

2023-10-31 17:12 UTC, FoxxoTrystan approved these changes

2023-11-01 01:24 UTC, Cheackraze approved these changes

2023-11-01 01:24 UTC, merged