NT14-WaveShot
new-frontiers-14/frontier-station-14 pull request #540
Opened 2023-11-05 16:43 UTC by Lokey82

## About the PR
Adds the NT14-WaveShot, The long-awaited reporter ship based on the Goonstation Radio Lab. This ship has been fit to serve the purpose of a news station with a reporter's office centerpiece that contains even two portable entertainment cameras and a mass-media console. This ship currently goes for a nice 40 thousand spessos and is well worth the price with its many luxurious amenities including but not limited to many vending machines, A captain's quarters, and of course the reporter's office plus a waiting room.

I hope that you get to see this ship soon amongst the cosmos at a Frontier outpost near you!

NOTE: NT14-WaveShot.PNG is an unrequired file, It purely exists on this commit to show off the ship.
NOTE 2: This ship was mapped upstream, Although it should merge just fine, Please keep this in mind.
## Why / Balance
I felt like making a ship and noticed there were no reporter ships.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: CentCom has become fed up with supplying Esquires with mass-media consoles, so they have contracted the help of a new ship engineer. Please welcome the NT14-WaveShot, A new ship for reporters!

2023-11-05 18:23 UTC, FoxxoTrystan approved these changes
- File name should be "waveshot" as NT14 will be auto-generated, best to keep lowcaps on files names.
- Uneeded PNG File (copy and paste image on your PR Info that works)
- Missing Shipyard file.
- Made on upstream? this already cause a ton of issues due to component and ent that are only on Frontier.
- Incorrect Fax machine, replace it with a Ship Fax Machine.
- No Jobs Spawns (Is it normal?)
- No ShipWarpPoint.
- No LateJoinPoint. (If there no jobs to add then i supose this is uneeded)
- Missing "Becomestation" component.
- Bridge airlock are command locked, nobody will be able to open those doors.

Suggestions:
- Missing Piping color, use colornetwork.
- Avoid adding a Mass Scanner Console on ships that do not need it. (should be kept for bounty hunting ships, expeditions, ect...)
- Internal doors should be normal solid walls and not reinforced walls, reinforced walls should be kept for the external hull.
- 3 APC connect the same LV, this should be avoided.

2023-11-05 18:23 UTC, FoxxoTrystan commented on Resources/Maps/Shuttles/NT14-WaveShot.PNG
- This file should not be here.
Merge request that are open should be the final product.

2023-11-05 18:26 UTC, FoxxoTrystan requested changes
- File name should be "waveshot" as NT14 will be auto-generated, best to keep lowcaps on files names.
- Uneeded PNG File (copy and paste image on your PR Info that works)
- Missing Shipyard file.
- Made on upstream? this already cause a ton of issues due to component and ent that are only on Frontier.
- Incorrect Fax machine, replace it with a Ship Fax Machine.
- No Jobs Spawns (Is it normal?)
- No ShipWarpPoint.
- No LateJoinPoint. (If there no jobs to add then i supose this is uneeded)
- Missing "Becomestation" component.
- Bridge airlock are command locked, nobody will be able to open those doors.

Suggestions:
- Missing Piping color, use colornetwork.
- Avoid adding a Mass Scanner Console on ships that do not need it. (should be kept for bounty hunting ships, expeditions, ect...)
- Internal doors should be normal solid walls and not reinforced walls, reinforced walls should be kept for the external hull.
- 3 APC connect the same LV, this should be avoided.

2023-11-09 23:45 UTC, Lokey82 commented
It is with great regret that I announce the closure of this PR, Due to multiple issues including the ones pointed out. This ship cannot be added to the game. I found solutions to these problems but unfortunately could not apply them. My inability to take the development of this project further and allow its implementation into the game is why I will be closing this PR as the ship would only sit uselessly in the mass of the other PRs here. If I can apply the solutions to the problems occurring I may return to this project in the future. But for now, I bid you all farewell and thank you for the opportunity to attempt to work on this amazing game.

2023-11-09 23:51 UTC, Cheackraze commented
what issues did you have? Dont let our slower dev process deter you, and I appologize for not getting to it sooner, but I have been typically doing ship reviews just once a week.  I would love to see this in game still, get at me on discord so I can help you get it sorted

2023-11-10 03:15 UTC, Lokey82 commented
Please disregard the closure of this pull request as stated in my previous comment. Thanks to the help of the wonderful developers of this game all issues have been solved and progress has resumed.

2023-11-10 03:16 UTC, Lokey82 commented on Resources/Maps/Shuttles/NT14-WaveShot.PNG
All of your issues mentioned have been solved in the latest commit, Thank you for your feedback.

2023-11-10 03:22 UTC, Lokey82 commented on RobustToolbox
Honestly, I have no clue why this one is here. I think I fucked up when committing.

2023-11-10 03:23 UTC, Lokey82 commented on RobustToolbox
Feel free to direct me to a fix as I got no clue what to do.

2023-11-10 05:30 UTC, Cheackraze commented on RobustToolbox
looks like it slipped in by mistake. you can take your saved map file and revert this commit, re-apply the map file and make a new commit. If you have more troubles, I can help fix it for you in a day or so

2023-11-12 19:00 UTC, Cheackraze commented
I added the shipyard prototype and finished up the remaining issues of the components and locked doors, it should be gtg

2023-11-12 19:20 UTC, Lokey82 commented
Ah, I just pushed a commit for the shipyard file and all that stuff. I guess git didn't email me that you did that.

2023-11-12 20:52 UTC, Cheackraze approved these changes

2023-11-12 20:53 UTC, merged