Adds a new ship, the NC Loader.
new-frontiers-14/frontier-station-14 pull request #589
Opened 2023-11-17 04:23 UTC by SurfinNinja1

## About the PR

A new cargo ship, the NC Loader, has finished development and is ready to be rolled out to Frontier Outpost!  With a tentative price of 16,000 spesos, this compact cargo carrier has all the necessary necessities needed for anyone who wishes to haul freight for profit.  Amenities include a conveyor belt assembly next to the docking airlocks (I can smell the spaghetti from here!), a moderately sized cargo hold with room for 10 crates(even more if you want to go beyond the catwalks!), and a break room with an arcade machine and soda dispenser.
## Why / Balance

I like doing solo cargo runs and noticed there were no ships made for that, so I decided just to build one myself.  I also had never built a ship before so this was a fun learning experience (save for me messing up files and having to rebuild it TWICE).

## Technical details

I followed the youtube guide. There are no code changes here.
## Media
![NC Loader](https://github.com/new-frontiers-14/frontier-station-14/assets/151105304/abbfd0ee-155f-4f67-b78e-ccf988b100e0)

- [ ✔️ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
add: NC Loader

2023-11-17 21:46 UTC, Everturning commented
It seems a bit too similar to the Chisel, which is bigger. I see the arcade machine as the only real difference, with a lot of aspects being the same (three drinks, PACMAN generator, captain's locker) and the main attraction being the cheap price.

2023-11-17 22:45 UTC, YumiGumi commented
> It seems a bit too similar to the Chisel, which is bigger. I see the arcade machine as the only real difference, with a lot of aspects being the same (three drinks, PACMAN generator, captain's locker) and the main attraction being the cheap price.

this is a cargo shuttle, not a mining shuttle, doesn't even have an ore processor

2023-11-18 03:22 UTC, SurfinNinja1 commented
> It seems a bit too similar to the Chisel, which is bigger. I see the arcade machine as the only real difference, with a lot of aspects being the same (three drinks, PACMAN generator, captain's locker) and the main attraction being the cheap price.

As Yumi pointed out, this vessel is meant for cargo, not mining.  PACMAN generators are common to most small and medium ships, as are captain's lockers.  As for the 3 glasses, I only had 3 there because people in the discord thought that 2 was not enough.

2023-11-22 17:20 UTC, Cheackraze commented
this is a super cute little cargo truck. Like a spess pickup truck. I like it.

2023-11-22 17:23 UTC, Cheackraze requested changes

2023-11-22 17:23 UTC, Cheackraze commented on Resources/Maps/Shuttles/Loader.yml
lowercase names only please

2023-11-22 17:56 UTC, merged

2023-11-22 22:35 UTC, Cheackraze commented on Resources/Maps/Shuttles/loader.yml
> +    - id: loader
this doesnt match properly