Adds medium sized vessel the Congregation, with chapel, soup kitchen,…
new-frontiers-14/frontier-station-14 pull request #595
Opened 2023-11-18 00:22 UTC by anonm0135

… medbay, and dorms to give opportunities for both charity and small earnings with an RP not moneymaking focus. (PLEASE LOOK THIS OVER, FIRST TIME SHUTTLE BUILDING.)

## About the PR
I created the mid sized shuttle the LB Congregation, a chaplain centric vessel with an RP focus to enable 'charity' work or charge for the services it can provide. The Ship is centered around a modest chapel, with a chaplains office, a small 'soup kitchen', a small medbay to treat people, and 6 2x2l dorm rooms with buttons that can be networked to enable bolting of their doors. Allowing a safe place for players to SSD without breaking immersion or being looted. Other features include a TV camera in the chapel, two hydro trays for the kitchen, and 2 withdraw only ATMs for charging services or donations. RP is the focus of this vessel not moneymaking but I believe between the kitchen, med, dorms, and 'donations' the owner could stand to earn a little bit during the course of their RP.

## Why / Balance
The mission is a great small shuttle, but lacks the facilities or space to enable more serious religious rp via charitable work. This vessel will enable larger groupings to take on the religious angle in rp in a variety of ways and encourages player interaction. It also could probably quickly result in cults doing cult things, maybe.

## Technical details
Ship appraised for like 32k, I set the price to 35k for now, as this isn't quite a moneymaker I figure a small margin is better for folks relative to its price. Uses 2 plasma generators by default. 300 something tiles so it is on the smaller end of midsized to maybe avoid clogging docks.

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

2023-11-18 03:01 UTC, Everturning commented
Image?

2023-11-18 03:46 UTC, anonm0135 commented
@Everturning Sorry I had the github links in there, must have messed something up when I posted it though, here they are:

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/150987437/858315e3-a965-4f6b-868a-3ff9f732b012)
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/150987437/bb88076c-e1e7-4c9e-9377-779c07b09b36)
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/150987437/30b95dbc-ed75-4d83-b26f-eb3a259e8b74)

2023-11-18 04:32 UTC, Everturning commented
looks sick, if not a bit more than "medium" size

2023-11-18 05:17 UTC, anonm0135 commented
Glad it looks decent, I hadn't intended it to be that size but it kinda just happened

2023-11-18 10:55 UTC, dvir001 commented
Either commit the old SpaceStation14.sln back or delete it from this commit since it was added by mistake.

2023-11-19 03:08 UTC, anonm0135 commented
> Either commit the old SpaceStation14.sln back or delete it from this commit since it was added by mistake.

I think I deleted it properly? Not 100%. Please let me know if anything else is needed on that.

2023-11-21 13:16 UTC, NeviNovat commented
I think that all windows need to have grills under them, like in other ships, might be a standard.
Looks cool and can be upgraded or modified to serve another purpose if need be!

2023-11-21 13:22 UTC, dvir001 commented on Resources/Maps/Shuttles/congregation.yml
There is a captain filled locker yet you added the same items it has again by mistake, remove the duplicated stuff and keep it as the base filled captain hardsuit locker please

2023-11-21 14:34 UTC, anonm0135 commented on Resources/Maps/Shuttles/congregation.yml
> There is a captain filled locker yet you added the same items it has again by mistake, remove the duplicated stuff and keep it as the base filled captain hardsuit locker please.
> 
> You also left a set of "ArmorCult", that's an EMAG armor set with stats of 50% protection against almost all damage types.

I was looking at a recent lilten video and it mentioned it was identical to captains armor. Do I need to remove it or could I simply not have the captains locker at all in exchange?

If the cult armor is a for sure nogo I will remove it and fix the cap locker.

2023-11-21 14:47 UTC, dvir001 commented on Resources/Maps/Shuttles/congregation.yml
Captain armor in this fork is much much lower on stats

2023-11-22 08:32 UTC, dvir001 commented
Also remove all wireless cameras routers / boards.

It exists on frontier with unlimited range. Having more then one exist has issues

2023-11-27 20:56 UTC, Cheackraze commented
I love the idea and design behind this ship. But I noticed something when testing. It appears that this map file was initialized, and isnt usable. You may have a backup file in the auto-save folder you can go back to. When mapping, always make sure to save a copy of it before you initialize and test, or it will break the map.

2023-11-27 20:57 UTC, Cheackraze commented
I did however update everything and fix the .sln issue for you. Be sure you are updating your project master before you continue working by using the fetch, pull, and sync options. If you need any more assistance, feel free to get ahold of us in the discord.

2023-11-30 21:36 UTC, Everturning commented
looks sick, will use if merged

2023-12-01 01:22 UTC, anonm0135 commented
> I did however update everything and fix the .sln issue for you. Be sure you are updating your project master before you continue working by using the fetch, pull, and sync options. If you need any more assistance, feel free to get ahold of us in the discord.

I'll rebuild it from scratch and resubmit here, I have a few changes now that I have had the chance to test it a bit that I want to make. Thank you all for your help and patience thus far.

2023-12-26 07:02 UTC, MagnusCrowe requested changes
Please reduce your med bay to just a morgue.  I don't want this ship to step on the toes of medical specialized ships.  Instead, you might consider filling that space with a **confessional** area.

I would like to see chaplain's focus on gaining the favor of the gods to revive people who are too rotten to be cloned, storing bodies until they can be revived, and using their chaplain powers to heal.

2024-01-14 14:40 UTC, MagnusCrowe commented
Going to close this for now because of inactivity.  Feel free to open it again when you're ready to start working on it again.

2024-01-14 14:40 UTC, closed without merging