[Large Shuttle] KL Monolith
new-frontiers-14/frontier-station-14 pull request #600
Opened 2023-11-18 20:30 UTC by CharcoalShipyard

## About the PR

The Kosmologistika Corporation has developed another ship exclusively for the Frontier Star Sector.
This large ship provides its crew with a wide range of capabilities. At first glance, you can say that everything is there, but don’t worry, because the Kosmologistika Corporation never gives more than necessary. The crew of a Monolith class vessel will be interested in filling empty spaces on the ship, as well as improving its starting condition.

## Why / Balance

Kosmologistika corporation wants to expand its sphere of influence by creating new ships.

## Technical details

Nothing was changed. The files in this PR are just shuttle files.

## Media
![monolith](https://github.com/new-frontiers-14/frontier-station-14/assets/150066944/2630cb41-6948-4a4a-b81f-cb6cd47519bd)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

No breaking changes here. 

**Changelog**
:cl:
- add: KL Monolith

2023-11-18 20:33 UTC, CharcoalShipyard commented
I don't know how to remove my previous work from the branch I've created.
My last ship was Bulker, and the files for It for some reason are still linkd...

2023-11-22 18:26 UTC, Cheackraze requested changes

2023-11-22 18:26 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/monolith.yml
> +  id: MONOLITH
Please use proper naming conventions. You have this all uppercased in random spots and it doesnt match either your own naming conventions and also doesnt match our naming standards. Please do not do this.

2023-11-22 18:26 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/monolith.yml
> +  id: MONOLITH
same here

2023-11-22 18:26 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/monolith.yml
> +    MONOLITH:
same here, do not do this. You will also need to change this if you did it on the BecomesStation component.

2023-11-27 20:59 UTC, Cheackraze commented
just bumping this to let you know, still awaiting changes

2024-01-14 14:41 UTC, MagnusCrowe commented
Going to close this for now because of inactivity.  Feel free to open it again when you're ready to start working on it again.

2024-01-14 14:41 UTC, closed without merging