Gourd fixes
new-frontiers-14/frontier-station-14 pull request #607
Opened 2023-11-21 18:55 UTC by YumiGumi

## About the PR
added cargo pallets, connected some cables, added some missing items

## Why / Balance
complaints regarding some issues, unable to receive rewards from expos, power backup

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- fix: lack of cargo pallets not allowing expo rewards to drop

2023-11-21 18:57 UTC, YumiGumi commented
realized i added this to a preexisting branch i made, the only required file is the most recent copy of the  gourd.yml ship file

2023-11-22 16:05 UTC, dvir001 requested changes

2023-11-22 16:05 UTC, dvir001 commented on Resources/Prototypes/_NF/Shipyard/gourd.yml
> +          mapNameTemplate: 'SLI Gourd {1}'
```suggestion
          mapNameTemplate: 'Gourd {1}'
```

2023-11-22 17:02 UTC, Cheackraze approved these changes

2023-11-22 17:19 UTC, merged