NT Stellaris
new-frontiers-14/frontier-station-14 pull request #615
Opened 2023-11-24 20:25 UTC by Lokey82

## About the PR

Adds the NT Stellaris, A new theatre ship.
## Why / Balance

## Technical details

## Media

![Stellaris - MEDIA](https://github.com/new-frontiers-14/frontier-station-14/assets/149951919/e71d4fe9-16b8-4ae8-8899-f1b5d7ab54c4)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the NT Stellaris, A new theatre ship.

2023-11-24 20:30 UTC, dvir001 commented on Resources/Prototypes/_NF/Shipyard/stellaris.yml
> +          mapNameTemplate: '{0} stellaris {1}'
```suggestion
          mapNameTemplate: 'stellaris {1}'
```

2023-11-24 20:33 UTC, dvir001 commented
Missing plasma next to generator

2023-11-24 20:37 UTC, Lokey82 commented
Fix 002 here adds the plasma next to the generator and a RTG as the production wasn't meeting load before.
as for the shipyard file error, Nice catch!

2023-11-24 20:37 UTC, dvir001 commented
> RTG

I think there is a rule about no RTG

2023-11-24 20:38 UTC, Lokey82 commented
Really? I know the esquire has one

2023-11-24 20:39 UTC, Lokey82 commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/149951919/9103de3c-25cc-4c0a-b97c-80e5f199263e)
If you look in engineering the Esquire does indeed have a RTG

2023-11-24 20:40 UTC, dvir001 commented
> ![image](https://private-user-images.githubusercontent.com/149951919/285541439-9103de3c-25cc-4c0a-b97c-80e5f199263e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4NTg2NzIsIm5iZiI6MTcwMDg1ODM3MiwicGF0aCI6Ii8xNDk5NTE5MTkvMjg1NTQxNDM5LTkxMDNkZTNjLTI1Y2MtNGMwYS1iOTdjLTgwZTVmMTk5MjYzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyNFQyMDM5MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjlkMWE1NzlhMGExMWYzNjE0MWQ3ZDQ4YWRiYzZjYmViYTZkMjZiNTFhOGQxMjBiNTg1ODExNTA2ZTAwZGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ncTi_mKOZYPABYnz_SXXD5BY39v_FcbjUZsOJI3DyTI) If you look in engineering the Esquire does indeed have a RTG

I need to get around to removing it since people buy to scrap them off.

2023-11-27 22:18 UTC, Cheackraze commented
i love the idea and concept of the ship but I think it could use a bit *more* to it, especially in the backstage area. Pics and suggestions to follow...

2023-11-27 22:26 UTC, Lokey82 commented
> i love the idea and concept of the ship but I think it could use a bit _more_ to it, especially in the backstage area. Pics and suggestions to follow...

Yeah, I apologize for the outdated media, I made a lot of changes that did fill up the ship a bit more but didn't have time at the moment to update the media, Expect that update soon.

2023-11-27 22:30 UTC, Cheackraze commented
> > i love the idea and concept of the ship but I think it could use a bit _more_ to it, especially in the backstage area. Pics and suggestions to follow...
> 
> Yeah, I apologize for the outdated media, I made a lot of changes that did fill up the ship a bit more but didn't have time at the moment to update the media, Expect that update soon.

i got you, here were my suggestions based on the original image

![stellaris ship](https://github.com/new-frontiers-14/frontier-station-14/assets/71046427/bd657995-dd3e-4d0d-aadd-e8a24631120f)

2023-11-30 03:47 UTC, Lokey82 commented
This should fix everything you mentioned, Also the media has been updated.

2023-12-11 17:50 UTC, Cheackraze requested changes

2023-12-11 17:50 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/stellaris.yml
yml linter detected you used tabs here instead of regular spaces. Once thats done, this looks good to go. I noticed on your waveshot ship, you forgot the warp point and spawn points, be sure we are including all of these on the ship. It needs late join spawner, observer warp point [ship variant], and job spawners for whichever jobs you want to be able to join here from the late join menu.

2023-12-11 23:28 UTC, Lokey82 commented on Resources/Prototypes/_NF/Shipyard/stellaris.yml
Rest assured, All of those are included. But would you mind elaborating on the tabs instead of spaces?

2023-12-18 20:54 UTC, Cheackraze approved these changes

2023-12-18 21:15 UTC, Cheackraze requested changes
fix those things and this is good to merge

2023-12-18 21:15 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/stellaris.yml
> +  price: 30000
this is too low, the ship is appraising at 36,000 when purchased. Raise it to 41,000 minimum

2023-12-18 21:15 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/stellaris.yml
> +  id: Stellaris
you have something mismatched on your prototype file and its causing the ship to not spawn correctly. Make sure all of your IDs match and that the becomesStation component field matches the entries here.

2023-12-18 23:49 UTC, Lokey82 commented
> fix those things and this is good to merge

All patched up!
Please let me know if there are any more problems.

2023-12-25 08:25 UTC, MagnusCrowe commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/8b8cd9d2-7702-4d99-b281-81b59f7088a1)
Color your pipes and use a standard locker, no custom fill for the captain's locker.

2023-12-25 08:28 UTC, MagnusCrowe commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/3c53a077-3608-4373-90cb-ad63f866d654)
Please add wheelchair accessibility.

2023-12-25 08:33 UTC, MagnusCrowe commented
Add a late join spawn point.

2023-12-25 08:36 UTC, MagnusCrowe commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/055f7cbb-0472-4b0b-8ed3-bc001a17a249)
Change the sec caps to regular red caps.

2024-01-14 16:08 UTC, MagnusCrowe approved these changes

2024-01-14 16:10 UTC, Cheackraze approved these changes

2024-01-14 16:11 UTC, merged