Textures for mercenary locker, mercenary airlocks
new-frontiers-14/frontier-station-14 pull request #620
Opened 2023-11-28 23:18 UTC by ErhardSteinhauer

## About the PR
Made textures for mercenary locker, airlocks (standard and glass) and ID overlay.

## Why / Balance
Uhh..

## Media
![mercenary](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/9e15bcb9-b244-483a-ad76-f671102c9142)
![mercenary_door](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/7201cddf-5195-4501-85b5-16b9c9db49ac)
![mercenary_open](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/326c5994-f49f-48c5-8240-49384a061456)

![opening](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/3aa685f1-8f23-43c8-8158-a0bcc2bb2fe8)
![opening](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/77c90f4e-978c-4227-a50c-499f8e6546b5)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**
:cl:
- add: Textures for Mercenary Locker, Mercenary Airlocks

2023-12-01 17:19 UTC, Cheackraze requested changes
other than the extra file, it seems like you've forgotten to add meta.json files to some of these texture folders

2023-12-01 17:19 UTC, Cheackraze commented on Resources/Textures/_NF/Clothing/Back/Duffels/mercenary.rsi/merc-inhand-left.xcf
this snuck in here, should remove

2023-12-04 17:28 UTC, Cheackraze commented
the RSI validator says some of your meta files are incorrect still on these

2023-12-04 21:27 UTC, ErhardSteinhauer commented
Alright, I think I fixed issues with meta.json files flagged by RSI validator

2023-12-04 22:51 UTC, ErhardSteinhauer commented on Resources/Textures/_NF/Clothing/Back/Duffels/mercenary.rsi/merc-inhand-left.xcf
deleted

2023-12-10 17:43 UTC, Cheackraze approved these changes

2023-12-10 17:43 UTC, merged