The Garden - A small botany ship
new-frontiers-14/frontier-station-14 pull request #701
Opened 2023-12-14 20:23 UTC by DustScoundrel

## About the PR

I added the Garden, a small-sized botany ship with sequestered grow bays and a full horticulture setup. Designed for the green thumbs amongst us.

## Why / Balance

## Technical details

## Media

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/152191535/0c0e416e-0aac-4852-aff8-3875f496cf28)
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/152191535/914f8130-9282-47a1-b9ef-c2c21cdab78a)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added the Garden, a small botany vessel.

2023-12-14 20:51 UTC, dvir001 commented
No PDA
It has free ID with permission in it

2023-12-14 21:01 UTC, DustScoundrel commented
Ah, damn. I just wanted it there for flavor. I'll remove it

2023-12-15 02:32 UTC, DustScoundrel commented
PDA has been removed. Now I just need to figure out how to make the change

2023-12-15 21:47 UTC, FoxxoTrystan requested changes
PDA need to be indeed removed.

And remove the HS infront of the name as we removed tags from all ships to avoid looong names.

2023-12-18 22:36 UTC, FoxxoTrystan approved these changes

2023-12-21 20:41 UTC, Cheackraze commented on Resources/Prototypes/_NF/Shipyard/garden.yml
> +  price: 29750
it was only worth around 16000 when I spawned it in. Im gunna change this to be a tad cheaper, maybe make it just barely purcahaseable for a new character.

2023-12-21 20:41 UTC, Cheackraze approved these changes

2023-12-21 21:08 UTC, merged