Omnichurch beacon update
new-frontiers-14/frontier-station-14 pull request #741
Opened 2023-12-22 23:02 UTC by DustScoundrel

## About the PR

- Fixed the connection to the outer APC to ensure the entire station is powered.
- Added two signs to the docking entrance welcoming visitors to the Beacon outpost, to give a little flavor.
- Changed names and descriptions of the APCs and air alarms to help define rooms.

## Why / Balance

## Technical details

## Media

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

**Changelog**

:cl:
- add: Added labels to room components to help define Beacon's rooms.
- fix: Fixed outer grounds APC wiring.
-->

2023-12-23 23:55 UTC, Cheackraze commented on Resources/Maps/Bluespace/grifty.yml
Lookers like you committed a few extra files

2024-01-07 11:45 UTC, dvir001 requested changes
I moved the file to the new location, deleted the extra files, I need you to please fix the warp and the fax so we can get this update in,

Thanks.

2024-01-07 11:45 UTC, dvir001 commented on Resources/Maps/_NF/POI/beacon.yml
> -      type: WarpPoint
Warp broken again

2024-01-07 11:45 UTC, dvir001 commented on Resources/Maps/_NF/POI/beacon.yml
> -      type: FaxMachine
Fax broken again.

2024-01-07 21:33 UTC, dvir001 commented
@DustScoundrel If you can update your PR to solve conflicts its good to go.

2024-01-14 02:06 UTC, dvir001 commented
Moved this to a new PR https://github.com/new-frontiers-14/frontier-station-14/pull/880
So I can keep it merged with master.

2024-01-14 22:30 UTC, dvir001 commented
Closed this for the active PR.

2024-01-14 22:30 UTC, closed without merging