Diagonal walls&windows
new-frontiers-14/frontier-station-14 pull request #757
Opened 2023-12-25 00:11 UTC by ErhardSteinhauer

## About the PR
New entities:
- Diagonal walls: grille, wood, reinforced and uranium.
- Diagonal windows: glass, reinforced glass, plasma, reinforced plasma.
- Secret door (can be constructed): wood, reinforced, shuttle, uranium.
- Wallmount (can be constructed): notice board (stores paper).

## Why / Balance
More structures for mappers and smugglers.

## Technical details
new .yml and .rsi

## Media
![2023-12-25_03 00 44](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/31c66e10-32e7-41e0-bb23-0c4c73c0ccdf)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- add: Added buildable entities: notice board, secret doors (wood, reinforced, shuttle, uranium).

2023-12-26 11:02 UTC, dvir001 requested changes

2023-12-26 11:05 UTC, FoxxoTrystan requested changes

2023-12-26 11:05 UTC, FoxxoTrystan commented on Resources/Prototypes/_NF/Entities/Structures/Walls/diagonal_walls.yml
WallShuttleDiagonal should not be a parent of Diagonals walls, this parent got reflective

2023-12-26 11:05 UTC, FoxxoTrystan commented on Resources/Prototypes/_NF/Entities/Structures/Walls/grille_diagonal.yml
Same issue:

WallShuttleDiagonal should not be a parent of Diagonals walls, this parent got reflective

2023-12-26 11:09 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Structures/Walls/diagonal_walls.yml
> WallShuttleDiagonal should not be a parent of Diagonals walls, this parent got reflective

It is parent for solid diagonal wall in the base game. I can explicitly specify the reflective component as 0.

2023-12-26 11:09 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Structures/Doors/secret_door.yml
Sure

2023-12-26 11:13 UTC, ErhardSteinhauer commented on Resources/Prototypes/_NF/Entities/Structures/Windows/window.yml
My bad thought that it from my previous iteration of this branch

2023-12-27 11:52 UTC, ErhardSteinhauer commented
Changed a few things around:
- Kegs moved to separate PR.
- Notice board moved to separate PR.
- Changed parent on diagonal windows from `BaseItem` to `Window`.
- Changed parent on diagonal walls from `WallShuttleDiagonal` to `WallSolidDiagonal`.
- Removed resistances from secret doors.
- Restored `windows.yml`.

2023-12-27 12:13 UTC, ErhardSteinhauer commented
Made so diagonal windows inherit from their respective base variations: eg., diagonal plasma window inherits from plasma window etc.

2024-01-08 01:37 UTC, dvir001 commented
I made multi parents changed to walls, all seem fine to me after testing, please confirm on your side its all good.

2024-01-08 01:37 UTC, dvir001 approved these changes

2024-01-08 04:07 UTC, ErhardSteinhauer commented
> I made multi parents changed to walls, all seem fine to me after testing, please confirm on your side its all good.

Your version works but I made some changes too and those appear to work fine on my end:
- Added new entity to use as a parent instead of WallSolidDiagonal (which inherits from WallShuttleDiagonal and has reflect component) - BaseWallDiagonal.
- Replaced WallSolidDiagonal with BaseWallDiagonal everywhere.

2024-01-08 04:08 UTC, ErhardSteinhauer commented
Also what's up with Map Prototype Checker throwing errors?

2024-01-10 04:20 UTC, ErhardSteinhauer commented
Moving diagonal windows and grille to a separate PR, leaving here here diagonal walls and secret doors.

2024-01-10 04:23 UTC, FoxxoTrystan approved these changes

2024-02-12 21:08 UTC, merged