Whiskey
new-frontiers-14/frontier-station-14 pull request #763
Opened 2023-12-26 01:13 UTC by cite2000

## About the PR
Adding the NSFD "Whiskey" ship.

## Why / Balance
I felt NFSD needed a heavy rescue ship since the next best medical vessel is the Hospitaller which isn't always the best when there's more than one injured or dead.

## Media
![bottomhalf init whiskey](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/49781421-ea4c-4ecc-a013-9c0d01188568)
![bottomhalf whiskey](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/47d4478c-05f9-489b-9e61-c27d8648b289)
![tophalf init whiskey](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/addf35a0-e286-46ec-9e79-092f368ae518)
![tophalf whiskey](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/b539fcb4-1c17-4154-9bea-42c626693e9e)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: NFSD medical ship "Whiskey"

2023-12-30 09:00 UTC, FoxxoTrystan approved these changes

2023-12-30 11:04 UTC, TsjipTsjip requested changes
Bunch of notes, this ship also needs a maintainer to give their approval on it before it is merged in the sense of the concept. I'm not sure if we need this ship on the security's ship catalog.

2023-12-30 11:04 UTC, TsjipTsjip commented on Resources/Maps/Shuttles/whiskey.yml
We should seriously consider whether or not we want this kind of ship in frontier.

Major notes:
- Are these holding cells? 1-tile? This has to be remediated.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/8d38d9be-85f0-495f-97a5-46a959acf4fe)
- Remove the loose headset.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/9ceb0a2d-c7ef-4bfa-a1ba-4c1f7628e4d2)
- Table through directional window.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/3db287c5-977d-4ab9-918c-8abe754c658a)
- Cloning on a non-flagship feels iffy. The Helix having it is already a bit of a stretch, but acceptable as it is _purely_ medical, not a security ship. Also equipment is clipping with the directional windows.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/1c0f5d90-cdb1-4fcd-887d-452c2d107216)
- Engineering feels very overkill for what is essentially a shuttle meant to be manned by two brigmedics. Remove the engineering locker for starters, superpacman feels overkill and should be replaced with two regular pacmans. It just feels too over-equipped.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/4fbe6fff-666d-4f78-a335-7be730d05c56)

Minor notes:
- Doctors should not be smoking. That's just opinion tho.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/c2db6957-2b4e-4170-a559-56c95a053acb)

As it stands, this ship is not ready to be merged and needs a bit of work still.

2023-12-30 11:07 UTC, TsjipTsjip commented
Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.

2023-12-31 09:14 UTC, TsjipTsjip commented on Resources/Prototypes/_NF/Shipyard/whiskey.yml
This is resolved in aa3382172b74815d94c7d0a8eb275acb9e12f037 .

2023-12-31 09:24 UTC, YumiGumi commented
> Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.

glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.

2023-12-31 09:52 UTC, dvir001 commented
> > Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.
> 
> glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.

I agree that glass underneath the thrusters feels very weird, logic wise it should not be a thing and it makes then look disconnected from the shuttle

This is something that should be updated and fixed with older ships who were held to different map standards before.

Were getting more hyper critical as were getting ships who add more mapper maintainers upkeep while having issues that could have been fixed while they were still being worked on, then having someone else fix later.

Look at how many shuttles had to get full atmost redone in the past 2 weeks since this was not a requirement for smalls ships before.

There is a baseline doc coming out soon to help streamline this process to have mapping more clear.

2023-12-31 10:08 UTC, YumiGumi commented
> > > Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.
> > 
> > 
> > glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.
> 
> I agree that glass underneath the thrusters feels very weird, logic wise it should not be a thing and it makes then look disconnected from the shuttle
> 
> This is something that should be updated and fixed with older ships who were held to different map standards before.
> 
> Were getting more hyper critical as were getting ships who add more mapper maintainers upkeep while having issues that could have been fixed while they were still being worked on, then having someone else fix later.
> 
> Look at how many shuttles had to get full atmost redone in the past 2 weeks since this was not a requirement for smalls ships before.
> 
> There is a baseline doc coming out soon to help streamline this process to have mapping more clear.

the ship i'm specifically regarding was made by magnus in the last month.

2023-12-31 10:09 UTC, dvir001 commented
> > > > Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.
> > > 
> > > 
> > > glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.
> > 
> > 
> > I agree that glass underneath the thrusters feels very weird, logic wise it should not be a thing and it makes then look disconnected from the shuttle
> > This is something that should be updated and fixed with older ships who were held to different map standards before.
> > Were getting more hyper critical as were getting ships who add more mapper maintainers upkeep while having issues that could have been fixed while they were still being worked on, then having someone else fix later.
> > Look at how many shuttles had to get full atmost redone in the past 2 weeks since this was not a requirement for smalls ships before.
> > There is a baseline doc coming out soon to help streamline this process to have mapping more clear.
> 
> the ship i'm specifically regarding was made by magnus in the last month.

I dont care who made the ship, if its need to be changed it will.

2023-12-31 10:12 UTC, TsjipTsjip commented
> but i'll add you've been hyper critical of the ship since it's conception

The only comment I have made before about this ship on discord is that plastitanium walls felt weird. This was wrong, as I have since learned it's common practice. I am sorry you feel this way about my comments, I should add that I am not a maintainer and as such you're allowed to put all my feedback in the disposal unit if you so choose. If you know better than me when it comes to mapping, then do do that.

Aside from my final review that I'll leave on this PR in a minute or so which will only contain critical points, I am detaching myself from this pull request as I believe any more feedback I give will not be treated receptively.

2023-12-31 10:14 UTC, TsjipTsjip requested changes
- Spawning issue is resolved.
- Brigmed headset **has to be removed entirely**, it contains an NFSD key which should only ever be normally obtainable through spawning as a role, getting it from SR/Sheriff in a PTech, or via "illegal" means (i.e. artifacts, ...) (I know there is telecomms servers around, this will be remediated as well in a later PR effort.)

2023-12-31 10:17 UTC, dvir001 commented
> * Brigmed headset

Ill get the Brigmed headset

2023-12-31 10:18 UTC, dvir001 commented
Sorry about the close, this is a mistake on my part with the comment click.

2023-12-31 11:49 UTC, YumiGumi commented
e

> > > > > Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.
> > > > 
> > > > 
> > > > glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.
> > > 
> > > 
> > > I agree that glass underneath the thrusters feels very weird, logic wise it should not be a thing and it makes then look disconnected from the shuttle
> > > This is something that should be updated and fixed with older ships who were held to different map standards before.
> > > Were getting more hyper critical as were getting ships who add more mapper maintainers upkeep while having issues that could have been fixed while they were still being worked on, then having someone else fix later.
> > > Look at how many shuttles had to get full atmost redone in the past 2 weeks since this was not a requirement for smalls ships before.
> > > There is a baseline doc coming out soon to help streamline this process to have mapping more clear.
> > 
> > 
> > the ship i'm specifically regarding was made by magnus in the last month.
> 
> I dont care who made the ship, if its need to be changed it will.

Right, because a maintainer can do whatever they please and the rest of us get the shaft. The sheer amount of a headache that has become mapping recently has turned me off from wanting to contribute at all. I understand the mapping baselines are in the works at the moment, but don't have one ship be allowed one thing and then change that stance without fixing the lot. It's just getting to the point of if you're a maintainer then anything is free game to you, but when a contributor does something it's met with unfathomable scrutiny and issues. I respect the fact that as a maintainer magnus has a lot more free reign regarding implementation, but when one person follows the example set by said maintainer we get hounded and harassed for it. The fucking glass looks nice, it's transparent and doesn't impact the ship in any form except how you think it should look. Until you figure out what is and isn't acceptable and everyone starts mapping things to that, i think i'll just retire myself from contributing.

2023-12-31 20:44 UTC, cite2000 commented
> * Spawning issue is resolved.
> * Brigmed headset **has to be removed entirely**, it contains an NFSD key which should only ever be normally obtainable through spawning as a role, getting it from SR/Sheriff in a PTech, or via "illegal" means (i.e. artifacts, ...) (I know there is telecomms servers around, this will be remediated as well in a later PR effort.)

while this is the case will the hospitaller be changed to no longer include a headset with sec comms in it? will update to remove the headset shortly.

2023-12-31 20:46 UTC, TsjipTsjip commented
> while this is the case will the hospitaller be changed to no longer include a headset with sec comms in it? will update to remove the headset shortly.

I will add this to the list of things to do. Thanks for flagging it.

2023-12-31 20:48 UTC, cite2000 commented
> > while this is the case will the hospitaller be changed to no longer include a headset with sec comms in it? will update to remove the headset shortly.
> 
> I will add this to the list of things to do. Thanks for flagging it.

actually on further inspection quite a few sec ships have sec comms in them. every baliff locker has sec comms in it. as does every sheriff locker.

2023-12-31 20:50 UTC, TsjipTsjip commented
> actually on further inspection quite a few sec ships have sec comms in them. every baliff locker has sec comms in it. as does every sheriff locker.

If it's in the locker fill that points to an underlying issue... Gonna @dvir001 here cause they know what can and can't be removed from the locker fill without breaking something in the most horrible way imaginable. (Imagine a sheriff without comms!)

2023-12-31 20:54 UTC, cite2000 commented
> > actually on further inspection quite a few sec ships have sec comms in them. every baliff locker has sec comms in it. as does every sheriff locker.
> 
> If it's in the locker fill that points to an underlying issue... Gonna @dvir001 here cause they know what can and can't be removed from the locker fill without breaking something in the most horrible way imaginable. (Imagine a sheriff without comms!)

though one thing i fail to see the issue in is the generator, it does the exact same thing as a pacman generator but requires more expensive fuel, and i'd have to considerably change things in the ship to fit another generator in there. as it is i am working with quite limited space. and i could change the cells into 1x2 or 2x2 but that would change the layout of the doors.

2023-12-31 21:04 UTC, TsjipTsjip commented
> though one thing i fail to see the issue in is the generator, it does the exact same thing as a pacman generator but requires more expensive fuel, and i'd have to considerably change things in the ship to fit another generator in there.

While mostly opinion, an argument can be made that this ship will be bought and sold just for the SUPERPACMAN, as this is usually just expedition loot. I'm not the definitive source on this tho, so feel free to do what you like until a maintainer decides on this.

> and i could change the cells into 1x2 or 2x2 but that would change the layout of the doors. it isn't MEANT to be a prisoner transport, it's a medical vessel.

2x2 would be the very least that's acceptable. (Mostly in the "humane treatment of prisoners" category, we don't want to encourage officers to mistreat prisoners and having good areas for them is part of that.) Alternatively, if you feel this isn't a prisoner transport, I would just remove the holding cells entirely, replacing them with plastitanium walls. Having doubled up walls isn't necessary problematic, especially when there's nothing else you can do with it.

2024-01-01 00:29 UTC, cite2000 commented
> > though one thing i fail to see the issue in is the generator, it does the exact same thing as a pacman generator but requires more expensive fuel, and i'd have to considerably change things in the ship to fit another generator in there.
> 
> While mostly opinion, an argument can be made that this ship will be bought and sold just for the SUPERPACMAN, as this is usually just expedition loot. I'm not the definitive source on this tho, so feel free to do what you like until a maintainer decides on this.
> 
> > and i could change the cells into 1x2 or 2x2 but that would change the layout of the doors. it isn't MEANT to be a prisoner transport, it's a medical vessel.
> 
> 2x2 would be the very least that's acceptable. (Mostly in the "humane treatment of prisoners" category, we don't want to encourage officers to mistreat prisoners and having good areas for them is part of that.) Alternatively, if you feel this isn't a prisoner transport, I would just remove the holding cells entirely, replacing them with plastitanium walls. Having doubled up walls isn't necessary problematic, especially when there's nothing else you can do with it.

in theory could i just remove the headsets encryption and have it only give common?

2024-01-01 05:02 UTC, MagnusCrowe commented
> > > > Oh and also, the glass underneath the thrusters feels very weird. I'd just let those be lattice.
> > > 
> > > 
> > > glass instead of lattice looks cleaner and has been an accepted building practice. it's transparent so you don't have the lattice just sticking out, this example has been see on several other ships including several security vessels. I respect your opinion on the vessel, but i'll add you've been hyper critical of the ship since it's conception. Some people have their preferred building styles and I view these as a more of an artist's signature rather than it being so problematic.
> > 
> > 
> > I agree that glass underneath the thrusters feels very weird, logic wise it should not be a thing and it makes then look disconnected from the shuttle
> > This is something that should be updated and fixed with older ships who were held to different map standards before.
> > Were getting more hyper critical as were getting ships who add more mapper maintainers upkeep while having issues that could have been fixed while they were still being worked on, then having someone else fix later.
> > Look at how many shuttles had to get full atmost redone in the past 2 weeks since this was not a requirement for smalls ships before.
> > There is a baseline doc coming out soon to help streamline this process to have mapping more clear.
> 
> the ship i'm specifically regarding was made by magnus in the last month.

Don't drag me into this, I never put glass under thrusters.  I only use glass under diagonal walls.

2024-01-01 05:10 UTC, MagnusCrowe commented
> Right, because a maintainer can do whatever they please and the rest of us get the shaft. The sheer amount of a headache that has become mapping recently has turned me off from wanting to contribute at all. I understand the mapping baselines are in the works at the moment, but don't have one ship be allowed one thing and then change that stance without fixing the lot. It's just getting to the point of if you're a maintainer then anything is free game to you, but when a contributor does something it's met with unfathomable scrutiny and issues. I respect the fact that as a maintainer magnus has a lot more free reign regarding implementation, but when one person follows the example set by said maintainer we get hounded and harassed for it. The fucking glass looks nice, it's transparent and doesn't impact the ship in any form except how you think it should look. Until you figure out what is and isn't acceptable and everyone starts mapping things to that, i think i'll just retire myself from contributing.

First, I was not the one who made the comment about the glass floor under the thrusters (though I do agree, in this circumstance it makes the thrusters look like they are not mounted securely, RP reasoning).  Second, I never put glass under thrusters on the Opportunity.

I get no special treatment, I wasn't even a maintainer when the Opportunity was merged.  

My advice was to use glass under diagonal walls to make them appear more seamless and less blocky.

2024-01-01 06:24 UTC, cite2000 commented
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/3424c741-e82f-42a8-920f-d041ab87d3da)
a quick picture of the lattices and glass as an example, i can change this further if need be.

2024-01-03 08:42 UTC, TsjipTsjip commented
YML label is suspicious, potentially labeler is broken? Not this PR tho.

2024-01-03 08:47 UTC, TsjipTsjip commented
Okay so @cite2000 , during the course of your PR the location for **map** files (the one produced my `savegrid`) was changed to `Resources/Maps/_NF/Shuttles/`, to keep all Frontier stuff in its own folder. Could you move your map file to there? This should fix the labels on this PR.

2024-01-03 08:57 UTC, cite2000 commented
> YML label is suspicious, potentially labeler is broken? Not this PR tho. (No C# is added when a PR does not change any C# files.)

that's because i did a small change that only changed the price, not the ship itself.

2024-01-03 08:58 UTC, cite2000 commented
> Okay so @cite2000 , during the course of your PR the location for **map** files (the one produced my `savegrid`) was changed to `Resources/Maps/_NF/Shuttles/`, to keep all Frontier stuff in its own folder. Could you move your map file to there? This should fix the labels on this PR.

that.. isn't an actual path.

2024-01-09 06:32 UTC, Cheackraze commented
having the cloner on this ship is a no-go, i suggest turning that room into the singular holding cell if anything. The superpacman cant stay, its not allowed to be a round start buyable generator. Glass under thrusters is also a no-go, and on any other ship that has them should be changed to lattice. The comms issue is because theres just an overabundance of them everywhere because of being essentially double mapped and they are still too often ending up in hands of non-security, we still havent exactly landed on the perfect solution but for now we need to at least trim the free mapped ones.

Im going to say that overall everything @TsjipTsjip has said, I would have also mentioned.

Design-wise, I like the layout, however I feel in some areas your decal work is a bit too noisy.  I feel that the black and red diamond entry way is too noisy and only serves to hide the fact that that room is a bit awkward, empty, and a touch pointless.  You could use that space for some other form or function or at the very least put some chairs down for passengers or a bench or something, and the noisiness of the tiled pattern toned down a bit.

As an idea, I'm not opposed to a medium-sized brig-medic focused ship for the situations you describe in your original post.

2024-01-09 06:47 UTC, VividPups commented
@Cheackraze  Intercom was changed.

2024-02-10 17:23 UTC, dvir001 commented
@cite2000 I updated the PR for you to support the new update, new files location and new naming.
You can keep working on this PR after you run a pull for the changes made here.

Please make sure to use the new ship guide lines when working on this PR:
https://frontierstation14.com/index.php/Ship_Submission_Guidelines

2024-02-12 22:17 UTC, Cheackraze commented
if the picture in the post is accurate, this looks good to me @MagnusCrowe if you concur lets get this in

2024-02-19 21:53 UTC, MagnusCrowe commented
I'll review it today.

2024-02-20 15:05 UTC, MagnusCrowe requested changes
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/587fbca7-02d2-401a-bd99-ff635d8c2b7a)
Top to bottom:

- Please remove the cigarettes
- Please add vacuum tiles to your corners to prevent space wind from pulling up the glass
- Please move your late join spawn point so it's not on top of the table

After these are done, I will merge it

2024-03-11 02:20 UTC, cite2000 commented
so i failed to mention this but about a week ago i attempted to pull the changes made and launch it and have been unable to properly launch it since. quite possibly i might need to entirely remake it at this rate.

2024-03-11 02:25 UTC, VividPups commented
can you post the error code that you receive when trying to do it?

2024-03-11 23:00 UTC, Cheackraze commented
> so i failed to mention this but about a week ago i attempted to pull the changes made and launch it and have been unable to properly launch it since. quite possibly i might need to entirely remake it at this rate.

your work is all saved so far here on github, so in the worst case it would simply be deleting your local repository and pulling it fresh from here. Feel free to reach out on the discord if you're still having troubles

2024-03-14 21:57 UTC, cite2000 commented
here's a picture of basically what changed, that should be everything that was requested 
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/154713988/007fc367-7e0c-4df1-a33f-edb367b5a61e)

2024-03-16 21:45 UTC, MagnusCrowe approved these changes
I moved the cryo pump out from under the table, put plating under your grilled windows, replaced the generators with the ship version that runs on map init, and moved the files to the correct mapping folder /_NF/Shuttles/Security/whiskey.yml.

2024-03-16 21:53 UTC, merged