Barge Update
new-frontiers-14/frontier-station-14 pull request #772
Opened 2023-12-27 09:20 UTC by ErhardSteinhauer

## About the PR
Updated Barge:
- Added waste loop, mapped emergency lights.

## Why / Balance
To curb CO2 build up.

## Technical details
.yml changes

## Media
![2023-12-27_11 44 56](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/018b4a91-1cfe-4a94-9739-40c5dbe1ee83)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Tweaked Barge - added waste loop to atmos.

2023-12-27 13:24 UTC, TsjipTsjip commented
YML-wise, this PR is too complex to review by hand. I'll load this in-game in a bit.

2023-12-27 13:47 UTC, TsjipTsjip requested changes
Couple of things, the rest looks good to go.

2023-12-27 13:47 UTC, TsjipTsjip commented on Resources/Maps/Shuttles/mail.yml
This is a commit from a different PR and should be removed from this one.

2023-12-27 13:47 UTC, TsjipTsjip commented on Resources/Maps/Shuttles/barge.yml
This scrubber should be moved away from the wast piping itself for clarity, analogous to the vent in the same room.

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/19798667/31ee5ed9-9afa-471a-ab47-00cc75e046df)

2023-12-27 18:51 UTC, ErhardSteinhauer commented on Resources/Maps/Shuttles/mail.yml
idk how to "re-base" (or "re-master", hell, I don't even know the proper term for this)  the commit. Can make new one.

2023-12-27 18:51 UTC, ErhardSteinhauer commented on Resources/Maps/Shuttles/barge.yml
Aye.

2023-12-28 20:30 UTC, ErhardSteinhauer commented on Resources/Maps/Shuttles/barge.yml
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/f6253f71-fe2f-4fef-8281-2339c93ee3a7)

2023-12-28 20:31 UTC, ErhardSteinhauer commented on Resources/Maps/Shuttles/mail.yml
used google, re-based this branch to my master

2024-01-07 16:11 UTC, MagnusCrowe approved these changes

2024-01-07 16:12 UTC, merged