The Whippet, a Bare-Bones Cargo Hauler
new-frontiers-14/frontier-station-14 pull request #784
Opened 2023-12-29 05:49 UTC by Vytian

## About the PR

Sometimes you want a smaller operation while still being able to haul cargo and haul it fast. Does the loader have too many luxuries that could be taken up by cargo space? This fuselage with thrusters attached is sure to get you and your cargo to its destination nice and quick, with minimal space dedicated to crew amenities to maximize cargo space. Buy a Whippet today!

## Why / Balance

It'd be nice to have some more variety from just seeing the Loader whenever crews of one or two want to run cargo. Costs 17500 spesos to be competitive with the Loader.

## Technical details

Simply adds the Whippet shuttle model to the shipyard.

## Media

![Whippet](https://github.com/new-frontiers-14/frontier-station-14/assets/149720111/609a2c77-8555-4fe4-ab85-9e6324440534)

- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

- add: NC Whippet ship model to the shipyard

2023-12-30 00:53 UTC, FoxxoTrystan requested changes
• Missing LateJoin Spawn.
• Emercency O2/Captain locked need to use the Filled version and not fill it yourself.

2023-12-30 00:53 UTC, FoxxoTrystan commented on Resources/Prototypes/_NF/Shipyard/whippet.yml
> +  mapName: 'NC Whippet'
• Change mapname to "Whippet" and not "MC Whippet" to avoid long names in IFF.

2023-12-30 09:53 UTC, TsjipTsjip reviewed
See FoxxyTrystan's notes, additionally I would like to request you look into how your shuttle looks without all those catwalks everywhere in the cargo area. In my opinion, these make your shuttle look very busy.

Did not test this shuttle in-game, but the files look fine aside from already made notes.

2024-01-01 01:01 UTC, Vytian commented
Updated with the recommended changes. LateJoin Spawnpoint was already present, just under the cargotechnician spawnpoint instead of over it for some reason.

2024-01-02 06:38 UTC, Everturning commented
gonna say it. it looks like a....

inappropriate thing.

2024-01-03 03:54 UTC, Everturning commented
move the engines to the center more
add some sort of a drink

2024-01-24 01:53 UTC, MagnusCrowe commented
Going to close this for now due to inactivity. Please open it up again when you come back and work on it.

2024-01-24 01:53 UTC, closed without merging