Remove shitcurity and cargonia references
new-frontiers-14/frontier-station-14 pull request #836
Opened 2024-01-06 15:30 UTC by mnemosynium

## About the PR
Removes "Shitcurity" and "Cargonia" from entity descriptions.

## Why / Balance
"Shitcurity", and similarly "Cargonia", are harmful references in an MRP server.

## Media

- [X] This PR does not require an ingame showcase

## Breaking changes
N/A

**Changelog**
N/A

2024-01-06 15:45 UTC, Cheackraze commented
I agree with shitcurity, but am open to discussing why referencing cargonia is bad.

2024-01-06 15:47 UTC, dvir001 requested changes

2024-01-06 15:47 UTC, dvir001 commented on Resources/Maps/Shuttles/praeda.yml
> +    - desc: A banner displaying the colors of the cargo department.
``# Frontier - desc change``

2024-01-06 15:47 UTC, dvir001 commented on Resources/Prototypes/Entities/Clothing/Eyes/glasses.yml
> +  description: Useful for security. # Frontier
``# Frontier - description change``

2024-01-06 15:47 UTC, dvir001 commented on Resources/Prototypes/Entities/Clothing/Eyes/specific.yml
> +  description: Useful for security. # Frontier
``# Frontier - description change``

2024-01-06 15:47 UTC, dvir001 commented on Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
> +  description: A sweet and strongly alchoholic drink, made after numerous distillations and years of maturing. # Frontier
``# Frontier - description change``

2024-01-06 15:47 UTC, dvir001 commented on Resources/Prototypes/Entities/Structures/Decoration/banners.yml
> +  description: A banner displaying the colors of the security department. # Frontier
``# Frontier - description change``

2024-01-06 15:49 UTC, mnemosynium commented on Resources/Maps/Shuttles/praeda.yml
> +    - desc: A banner displaying the colors of the cargo department.
Is that needed in a Frontier ship file?

2024-01-06 15:53 UTC, dvir001 commented on Resources/Maps/Shuttles/praeda.yml
> +    - desc: A banner displaying the colors of the cargo department.
No need, didnt notice it was ship file.

2024-01-06 15:54 UTC, dvir001 commented on Resources/Prototypes/Entities/Structures/Decoration/banners.yml
> +  description: A banner displaying the colors of the security department. # Frontier
Forgor?

2024-01-06 15:56 UTC, dvir001 approved these changes

2024-01-06 15:57 UTC, dvir001 commented
> hy referencing cargonia is bad.

More of an upstream / baseline LRP gameplay meme.

2024-01-06 16:08 UTC, dvir001 commented
This going to mess with 
https://github.com/new-frontiers-14/frontier-station-14/pull/833
Please let the changes to that ship be done on the same PR so it wont be an issue to the rework if possible.

2024-01-07 15:28 UTC, dvir001 commented
Ill merge it tomorrow unless someone want to voice opinions about the cargonia parts, its seems most agree its more LRP.

2024-01-08 07:58 UTC, merged