CODEOWNERS
new-frontiers-14/frontier-station-14 pull request #883
Opened 2024-01-14 15:36 UTC by dvir001

## About the PR
Added the start of the CODEOWNERS file.

2024-01-14 15:42 UTC, FoxxoTrystan commented
Explain this file please.

2024-01-14 15:43 UTC, dvir001 commented
> Explain this file please.

It auto assign this:
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/39403717/969ab03b-5f2b-484c-94a2-fffd10c1769f)

2024-01-14 15:43 UTC, TsjipTsjip requested changes

2024-01-14 15:43 UTC, TsjipTsjip commented on .github/CODEOWNERS.txt
> +/github/workflows/frontier-mapchecker.yml @TsjipTsjip
Correct paths:
`.github/mapchecker/*`
`.github/workflows/frontier-mapchecker.yml`

2024-01-14 15:45 UTC, FoxxoTrystan commented
When this is aproved i may add some of my shuttles/code on it.

2024-01-14 15:45 UTC, dvir001 commented
> When this is aproved i may add some of my shuttles/code on it.

You can just send me the edit your want on Discord so I can quick add it

2024-01-14 22:38 UTC, dvir001 commented
Note this file is based on #863 with changes under the upstream uncommitted lines for the sake of no merge conflicts.

2024-01-24 13:38 UTC, dvir001 commented
We can really start using this for ships, I made sure this file wont have conflicts issue with the one coming from upsteam merge.

2024-02-15 01:45 UTC, Cheackraze approved these changes

2024-02-15 01:46 UTC, merged