added new black market ship with a cannon
new-frontiers-14/frontier-station-14 pull request #893
Opened 2024-01-22 10:20 UTC by MasterReef

## About the PR
 A new ship with a cannon called the ECS Alnitak! Blackmarket only.

## Why / Balance
I like spaceships and guns and so if i have a spaceship and i have a gun boom! Armed Spaceship!.

## Media
![2024-1-22_18 11 34](https://github.com/new-frontiers-14/frontier-station-14/assets/125022429/09eae318-8674-4d92-bf02-74bbda4b3de2)

- [ X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

**Changelog**

:cl:
- add: Added the first armed ship in the game, ECS Alnitak!

2024-01-22 10:24 UTC, MasterReef commented
would love for it to be added before artillery update

2024-01-22 10:26 UTC, dvir001 commented on SpaceStation14.sln
How to make the game not able to boot anymore in one simple step

2024-01-22 10:26 UTC, MasterReef commented on SpaceStation14.sln
wait is that needed?

2024-01-22 10:29 UTC, dvir001 commented on SpaceStation14.sln
Deleting a critical file in your PR that is need related to your ship is an issue.

2024-01-22 10:35 UTC, MasterReef commented on SpaceStation14.sln
how to fix?

2024-01-22 11:34 UTC, dvir001 commented on SpaceStation14.sln
Download it from repo, commit it.
Also move your shuttle to new folders under _NF

2024-01-22 12:23 UTC, MasterReef commented on SpaceStation14.sln
i dont know how to commit it back

2024-01-22 12:25 UTC, dvir001 commented
You still have changes on it, please download the one from this repo and push it to fix it.

2024-01-22 12:26 UTC, MasterReef commented on SpaceStation14.sln
i did it

2024-01-22 12:29 UTC, dvir001 commented on SpaceStation14.sln
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/39403717/e19f07a1-e7b3-45a8-a00c-ca74be29c564)

Use the one existing on this repo, you submitted your own one to replace it.

2024-01-22 12:35 UTC, MasterReef commented on SpaceStation14.sln
the script looks the same?

2024-01-22 12:44 UTC, MasterReef commented on SpaceStation14.sln
problem solved i guess.

2024-01-22 13:00 UTC, dvir001 commented
Also dont forget to move ship to Resources/Maps/_NF/Shuttles/alnitak.yml

2024-01-22 13:40 UTC, MasterReef commented
> > > Also dont forget to move ship to Resources/Maps/_NF/Shuttles/alnitak.yml
> > 
> > 
> > good now?
> 
> ![image](https://private-user-images.githubusercontent.com/39403717/298599976-c61df11f-af83-46bf-8b97-3b7f028faddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzExNDMsIm5iZiI6MTcwNTkzMDg0MywicGF0aCI6Ii8zOTQwMzcxNy8yOTg1OTk5NzYtYzYxZGYxMWYtYWY4My00NmJmLThiOTctM2I3ZjAyOGZhZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEzNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmVjODdlMTE5NDFkMDFiYzE2NGMyZDA2OTgyOTdhNWM2ZmY0ODdlYjFiN2VhYmI3MWZlOGZjYjQ0ZmU2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kNnP0HaYW90BH1MFm0BOw3uRJiiI0tKlDJ64PJkf3T4) Did you forgot to push?

done and dusted

2024-01-22 14:03 UTC, dvir001 commented
> > > > Also dont forget to move ship to Resources/Maps/_NF/Shuttles/alnitak.yml
> > > 
> > > 
> > > good now?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/39403717/298599976-c61df11f-af83-46bf-8b97-3b7f028faddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzExNDMsIm5iZiI6MTcwNTkzMDg0MywicGF0aCI6Ii8zOTQwMzcxNy8yOTg1OTk5NzYtYzYxZGYxMWYtYWY4My00NmJmLThiOTctM2I3ZjAyOGZhZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEzNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmVjODdlMTE5NDFkMDFiYzE2NGMyZDA2OTgyOTdhNWM2ZmY0ODdlYjFiN2VhYmI3MWZlOGZjYjQ0ZmU2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kNnP0HaYW90BH1MFm0BOw3uRJiiI0tKlDJ64PJkf3T4) Did you forgot to push?
> 
> done and dusted

You are killing me

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/39403717/18699c8b-09ba-4fd1-a99e-b948601e5ec1)

Also the ship shipyard yml need to point to new locations.

2024-01-22 14:11 UTC, MasterReef commented
> > > > > Also dont forget to move ship to Resources/Maps/_NF/Shuttles/alnitak.yml
> > > > 
> > > > 
> > > > good now?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/39403717/298599976-c61df11f-af83-46bf-8b97-3b7f028faddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzExNDMsIm5iZiI6MTcwNTkzMDg0MywicGF0aCI6Ii8zOTQwMzcxNy8yOTg1OTk5NzYtYzYxZGYxMWYtYWY4My00NmJmLThiOTctM2I3ZjAyOGZhZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEzNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmVjODdlMTE5NDFkMDFiYzE2NGMyZDA2OTgyOTdhNWM2ZmY0ODdlYjFiN2VhYmI3MWZlOGZjYjQ0ZmU2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kNnP0HaYW90BH1MFm0BOw3uRJiiI0tKlDJ64PJkf3T4) Did you forgot to push?
> > 
> > 
> > done and dusted
> 
> You are killing me
> 
> ![image](https://private-user-images.githubusercontent.com/39403717/298610382-18699c8b-09ba-4fd1-a99e-b948601e5ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzI5NTgsIm5iZiI6MTcwNTkzMjY1OCwicGF0aCI6Ii8zOTQwMzcxNy8yOTg2MTAzODItMTg2OTljOGItMDliYS00ZmQxLWE5OWUtYjk0ODYwMWU1ZWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE0MTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MjgzYzI1Mzc0NzkzZTY1MGUzOGM5NGJmODNhN2NjMmZmZGRjMTAxNDY1MmIwZjA3YjY5MmRlNzBkMjY1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bB5i86VCqMjdt__gmWiC_50uXoYhdEaRqQZg8kQ9ZDM)
> 
> Also the ship shipyard yml need to point to new locations.

Is it???? finally done??? i want to die!!!

2024-01-22 14:20 UTC, MasterReef commented
> > > > > Also dont forget to move ship to Resources/Maps/_NF/Shuttles/alnitak.yml
> > > > 
> > > > 
> > > > good now?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/39403717/298599976-c61df11f-af83-46bf-8b97-3b7f028faddf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzExNDMsIm5iZiI6MTcwNTkzMDg0MywicGF0aCI6Ii8zOTQwMzcxNy8yOTg1OTk5NzYtYzYxZGYxMWYtYWY4My00NmJmLThiOTctM2I3ZjAyOGZhZGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDEzNDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZmVjODdlMTE5NDFkMDFiYzE2NGMyZDA2OTgyOTdhNWM2ZmY0ODdlYjFiN2VhYmI3MWZlOGZjYjQ0ZmU2M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kNnP0HaYW90BH1MFm0BOw3uRJiiI0tKlDJ64PJkf3T4) Did you forgot to push?
> > 
> > 
> > done and dusted
> 
> You are killing me
> 
> ![image](https://private-user-images.githubusercontent.com/39403717/298610382-18699c8b-09ba-4fd1-a99e-b948601e5ec1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MzM0OTksIm5iZiI6MTcwNTkzMzE5OSwicGF0aCI6Ii8zOTQwMzcxNy8yOTg2MTAzODItMTg2OTljOGItMDliYS00ZmQxLWE5OWUtYjk0ODYwMWU1ZWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE0MTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDU5Mjk3ZjA2YjJhNzNjMjgxYTI4NmM1MTRjZmI1MjhlNTU4ODkyY2M4MjNjZTZiODgyZGIyNjE2ZDMyZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LPZ7-eP4Uwb_SH0hvZ_wxUt2ggVkQw3kqfTKrioDVG8)
> 
> Also the ship shipyard yml need to point to new locations.

aaaalllsooo ive read in one of a ships script and it tells me i need to 2 paths

2024-01-22 15:10 UTC, dvir001 commented
I fixed the files locations for you.

2024-02-19 21:03 UTC, Cheackraze commented
its a funny little ship, but we cant allow gas miners on ships like that. You can instead use the atmosfix markers to make them start pre-filled with a large amount of gas, but the miners would be exploited very badly.

2024-02-25 06:27 UTC, MasterReef commented
> @MasterReef could you reply to me the status of this, are you going to fix the issues soon ? Thank you in advance

Sorry for late reply, I will fix it when I can.

2024-02-25 06:54 UTC, MasterReef commented
> @MasterReef could you reply to me the status of this, are you going to fix the issues soon ? Thank you in advance

All fixed!

2024-02-25 17:53 UTC, MagnusCrowe requested changes
1. The cannon portion of the ship has 2 tiny fans where it technically needs none, due to the airlock...one at the most.  Same issue with the docking ports.
2. Your distro is all passive vents.  In the event of any spacing on your ship, everything will be spaced because of this.
3. The tiny cockpit has no scrubber, that will kill people.
4. Ship starts off with too many canisters of oxygen and plasma.
5. Remove the captain hardsuit locker.
6. Remove the chemical grenade stuff and the cryobeakers.
7. You have a sink under a light in your chem room, move one of the two please.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/ef7c3d5c-4827-482d-9f1b-ec45f826da89)
8. Your air alarm and APC should be rotated to face the correct direction.
9. You might want to include an "igniter" and a proper atmospheric setup in your cannon part so nobody will need to sacrifice themselves every time you want to fire.

Lastly, I think that this ship is too dependent on the server atmos settings.  IDK if it will even work with the current speed of atmos. 
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/6a55fece-ead0-4619-abb0-7dc0159410a3)

2024-02-25 18:10 UTC, MagnusCrowe commented
Also, you are missing a fax machine.
Please refer to https://frontierstation14.com/index.php/Ship_Submission_Guidelines for anything I may have forgotten.

2024-02-25 23:03 UTC, Cheackraze commented
i recently sped atmos up a tad and might do so again since its still not quite where I want it to be @MagnusCrowe. Theoretically, with plasma burn completed in that chamber, it _should_ work as a giant pneumatic cannon

2024-02-26 09:15 UTC, MasterReef commented
> 1. The cannon portion of the ship has 2 tiny fans where it technically needs none, due to the airlock...one at the most.  Same issue with the docking ports.
> 2. Your distro is all passive vents.  In the event of any spacing on your ship, everything will be spaced because of this.
> 3. The tiny cockpit has no scrubber, that will kill people.
> 4. Ship starts off with too many canisters of oxygen and plasma.
> 5. Remove the captain hardsuit locker.
> 6. Remove the chemical grenade stuff and the cryobeakers.
> 7. You have a sink under a light in your chem room, move one of the two please.
>    ![image](https://private-user-images.githubusercontent.com/124747282/307611183-ef7c3d5c-4827-482d-9f1b-ec45f826da89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzc4NzYsIm5iZiI6MTcwODkzNzU3NiwicGF0aCI6Ii8xMjQ3NDcyODIvMzA3NjExMTgzLWVmN2MzZDVjLTQ4MjctNDgyZC05ZjFiLWVjNDVmODI2ZGE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2U4NjZhYWQxNWY5NTQ2MWY0ZGUwNTNjYTM0YTQ4MTJhNGIzYTcwYmZlNjllNTAyODIyZGIwOWRmOTIyY2U2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xNwtKWmcwoo4wp-f5wF4QEs42E5A1MwgC6yUTRjCKCY)
> 8. Your air alarm and APC should be rotated to face the correct direction.
> 9. You might want to include an "igniter" and a proper atmospheric setup in your cannon part so nobody will need to sacrifice themselves every time you want to fire.
> 
> Lastly, I think that this ship is too dependent on the server atmos settings. IDK if it will even work with the current speed of atmos. ![image](https://private-user-images.githubusercontent.com/124747282/307611630-6a55fece-ead0-4619-abb0-7dc0159410a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mzc4NzYsIm5iZiI6MTcwODkzNzU3NiwicGF0aCI6Ii8xMjQ3NDcyODIvMzA3NjExNjMwLTZhNTVmZWNlLWVhZDAtNDYxOS1hYmIwLTdkYzAxNTk0MTBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjhhODJhZWY2Mjk0MzUxODcyMTZhZTAyZjJmMTQxNWQ4ZjMyY2FiZGVlM2RiOWQ3Y2RkM2NmM2Q3MjFlNzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7bJQOtoTmD1A95Zife_xTVHbW_r8puooOdwjPC8ERz8)

In the 2nd pic, you have to put the payload in the barrel, not in the ignition chamber.

I am gonna fix these when I can.

2024-02-26 13:52 UTC, MasterReef commented
> 1. The cannon portion of the ship has 2 tiny fans where it technically needs none, due to the airlock...one at the most.  Same issue with the docking ports.
> 2. Your distro is all passive vents.  In the event of any spacing on your ship, everything will be spaced because of this.
> 3. The tiny cockpit has no scrubber, that will kill people.
> 4. Ship starts off with too many canisters of oxygen and plasma.
> 5. Remove the captain hardsuit locker.
> 6. Remove the chemical grenade stuff and the cryobeakers.
> 7. You have a sink under a light in your chem room, move one of the two please.
>    ![image](https://private-user-images.githubusercontent.com/124747282/307611183-ef7c3d5c-4827-482d-9f1b-ec45f826da89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTUzMDQsIm5iZiI6MTcwODk1NTAwNCwicGF0aCI6Ii8xMjQ3NDcyODIvMzA3NjExMTgzLWVmN2MzZDVjLTQ4MjctNDgyZC05ZjFiLWVjNDVmODI2ZGE4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMzQzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzU3MTNkMjJlYzA5YTdkNGI0ZmQ3NmZiOWQzYWY5YzUyZDhmYWZjYWUwMzNhYmI1NzRlOGU5NDEwNmRiNjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Yxhg5NnEybfbcpp_Kyi22uv0sBIAbrHE9ley5hwyqi8)
> 8. Your air alarm and APC should be rotated to face the correct direction.
> 9. You might want to include an "igniter" and a proper atmospheric setup in your cannon part so nobody will need to sacrifice themselves every time you want to fire.
> 
> Lastly, I think that this ship is too dependent on the server atmos settings. IDK if it will even work with the current speed of atmos. ![image](https://private-user-images.githubusercontent.com/124747282/307611630-6a55fece-ead0-4619-abb0-7dc0159410a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTUzMDQsIm5iZiI6MTcwODk1NTAwNCwicGF0aCI6Ii8xMjQ3NDcyODIvMzA3NjExNjMwLTZhNTVmZWNlLWVhZDAtNDYxOS1hYmIwLTdkYzAxNTk0MTBhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxMzQzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzkyOTBjMDkzNTdkYmNkZDk1YzIzZGFjM2VkM2FiNWY2NmFiNDUwODFiZDJkNzU4ZDczMzg2MjAzYmIxYzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rcfqJM0JxbK8k9bRQypgIbKh4sc_89Jsz84rBR5ov_8)

Everything you told me is now fixed, if i missed some then tell me.

2024-02-26 13:57 UTC, MasterReef commented
> i recently sped atmos up a tad and might do so again since its still not quite where I want it to be @MagnusCrowe. Theoretically, with plasma burn completed in that chamber, it _should_ work as a giant pneumatic cannon

Ooooo thanks, Also do you know a way for cryogenic beakers that is filled with clf3 to explode on impact when thrown at walls from outside the station?

2024-03-01 01:46 UTC, MasterReef commented
I will be not available from 1/3 to 7/3. fyi if you guys want me to make changes.

2024-03-12 07:46 UTC, MasterReef commented
I am available now

2024-03-16 22:24 UTC, MagnusCrowe commented
Today in fact.

2024-03-19 08:41 UTC, MasterReef commented
> Today in fact.

Not meaning to be rude but.... is 2 days after the comment still today though?

No offense intended

2024-03-22 05:47 UTC, MagnusCrowe commented
You need to update your branch to the latest version on Frontier master, the version you're using is missing a lot of things.

1.  You need to replace the air vent in the burn chamber with a gas injector.
2. You don't need a disposals pipe to transport a lighter to the burn chamber, you can use a device called an igniter.
3. Instead, you can use the disposals pipe to load the cannon without going into space probably.
4. You need to replace the generators with the shuttle variant once your branch is up to date. These ones are automatically anchored, fueled, and running.
5. I recommend you replace the captain's and merc's locker with pirate lockers.
6. You can include a chem dispenser in your chemistry lab if you wish.
7. You don't need an air sensor in rooms with powered vents and scrubbers.  You only need air sensors in rooms without them, you might want to remove the one from the cargo area and add one to the burn chamber, to monitor the pressure and temperature remotely.
8. Link your burn chamber's airlock doors so that opening one bolts the other so they both cannot be opened at the same time.  That would be catastrophic.
9. The gas mixer in your atmos setup has 30% nitrogen and 70% oxygen, the incorrect ratio. It should be about 22% oxygen and 78% nitrogen.
10. You need to add a few emergency lights.
11. Your substation is located on a rear wall right behind your thrusters, a prime location to become EMPed...might reduce the ships value as a contraband vessel.
12. The ship's sell value and purchase price are really far off of eachother, was that intentional?

![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/27d9693d-a2b0-4a85-ab49-99cca4084efe)

2024-03-22 06:01 UTC, MagnusCrowe commented
Forgot a couple things.
1. You may want to add a fire extinguisher and a defib wall closet.
2. I'm confused why you have a passive vent under a wall.
3. Please route your cables under floor tiles and not under walls wherever possible.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/8680ca62-b084-489a-b20a-edd609280f27)

2024-03-22 14:33 UTC, MasterReef commented
> You need to update your branch to the latest version on Frontier master, the version you're using is missing a lot of things.
> 
> 1. You need to replace the air vent in the burn chamber with a gas injector.
> 2. You don't need a disposals pipe to transport a lighter to the burn chamber, you can use a device called an igniter.
> 3. Instead, you can use the disposals pipe to load the cannon without going into space probably.
> 4. You could probably also use disposals to drop grenades out the back of the ship to collide with people who chase you.
> 5. You need to replace the generators with the shuttle variant once your branch is up to date. These ones are automatically anchored, fueled, and running.
> 6. I recommend you replace the captain's and merc's locker with pirate lockers.
> 7. You can include a chem dispenser in your chemistry lab if you wish.
> 8. You don't need an air sensor in rooms with powered vents and scrubbers.  You only need air sensors in rooms without them, you might want to remove the one from the cargo area and add one to the burn chamber, to monitor the pressure and temperature remotely.
> 9. Link your burn chamber's airlock doors so that opening one bolts the other so they both cannot be opened at the same time.  That would be catastrophic.
> 10. The gas mixer in your atmos setup has 30% nitrogen and 70% oxygen, the incorrect ratio. It should be about 22% oxygen and 78% nitrogen.
> 11. You need to add a few emergency lights.
> 12. Your substation is located on a rear wall right behind your thrusters, a prime location to become EMPed...might reduce the ships value as a contraband vessel.
> 13. The ship's sell value and purchase price are really far off of eachother, was that intentional?
> 
> ![image](https://private-user-images.githubusercontent.com/124747282/315899003-27d9693d-a2b0-4a85-ab49-99cca4084efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMTc5ODksIm5iZiI6MTcxMTExNzY4OSwicGF0aCI6Ii8xMjQ3NDcyODIvMzE1ODk5MDAzLTI3ZDk2OTNkLWEyYjAtNGE4NS1hYjQ5LTk5Y2NhNDA4NGVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQxNDI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTY4NmM4YWZkMzc1Y2ZmNzMzOGE5MGU4YTI4YzBiOGJiMzE1NzUwMjZkMTVkYzYxMWM4OGVjODk5YjhkYTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6h6cne_CDSRk5ZOV52ksz7yIkwxCJ2kWoHeemeTRjJY)

Fixed, also the ignition chamber needs to warm up to fire, the pressure inside needs atleast 10-20k kpa.
Ship price is high cuz, you can fire a ton of ordinance in one shot and that can absolutely cut an entire ship in half. (If only chemical explosions work in places without atmos like how rpg works in space. Prob gonna add a new cannon ammo.)

Also theres wires in the in the walls of the barrel because the barrel does not have tiling.

2024-03-30 12:21 UTC, MasterReef commented
@MagnusCrowe Can you review this when you can?

2024-03-30 19:49 UTC, MagnusCrowe commented
> @MagnusCrowe Can you review this when you can?

Today/Tonight

2024-04-07 01:31 UTC, MagnusCrowe commented
You're going to need to update this branch before I do any more reviewing, sorry it's just so out of date.
See sec for example of how old this branch is.
![image](https://github.com/new-frontiers-14/frontier-station-14/assets/124747282/f30e4bce-1f29-4a51-bf8a-778abd74a438)

2024-04-08 08:54 UTC, dvir001 commented
Im closing this PR till you are doing a master pull into it, 
you can reopen it or ask us here to reopen it for you.
Or you can also just move the 2 files into a new PR on updated version of your fork.

2024-04-08 08:54 UTC, closed without merging

2024-04-12 08:48 UTC, MasterReef commented
I give up. This was here from January 22.