The Grand Arcadia Update
new-frontiers-14/frontier-station-14 pull request #906
Opened 2024-01-23 21:12 UTC by AjexRose

## About the PR

after finally getting off my ass, I decided to finally finish this, this PR adds a new bluespace event known as the "Arcadia Industries Data Carrier" A bluespace event within a fully operational shuttle, filled with lots of loot and entities to fight though. Also includes changes to the Arcadia Industries that were added awhile ago, mainly replacing their blood with oil, and making the Mobile Blaster Units space proof. 

## Why / Balance

Gives Arcadia Industries more visibility then just a vending machine. 
The high amount of loot within is countered by the fact that the shuttle is simply bursting from the seems with enemies, all ready to pounce at intruders.
The main focus is the R&D loot, which there isnt much attention for as of now in the Frontier. 
## Technical details

N/A
## Media

- [ ] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase
![Frontier Station 1_23_2024 2_34_38 PM](https://github.com/new-frontiers-14/frontier-station-14/assets/112997230/49560bf6-a3ee-455d-8fd0-f42f5a6e7d72)
![Frontier Station 1_23_2024 2_31_25 PM](https://github.com/new-frontiers-14/frontier-station-14/assets/112997230/843c07ec-fc70-4e60-bc8a-52e32f02fb5c)

## Breaking changes

**Changelog**

:cl: AjexRose
- add: Added a new bluespace event: The Data Carrier, with lots of loot, enemies, and a small focus on R&D
- tweak: Arcadia Industries mobs have been slightly reworked to no longer bleed blood.

2024-01-23 21:48 UTC, FoxxoTrystan requested changes
Remove Random Magic Book Spawner (Or at least use the safe one)

Recomendation/Notes:
* Wizard hardsuit seem compleatly out of place (but also because there was plan to put those in more wizard/alien looking asteroids)
* Atmos is ehh, started then gone?
* Floor need decals in my opinion a bit.
* Does your NPCs has the salvage component? if no they need it so they despawn when the ship despawn.
* Again make the ship name/annoncement to the default/random.

2024-01-23 21:48 UTC, FoxxoTrystan commented on Resources/Prototypes/_NF/Events/events.yml
> +    endAnnouncement: station-event-bluespace-ArcIndDataCarrier-end-announcement
Same here, prefer to use "station-event-bluespace-ship-end-announcement"

2024-01-23 22:10 UTC, AjexRose commented on Resources/Maps/_NF/Bluespace/DataCarrier.yml
> +    - name: AI-DC01-003
Done

2024-01-23 22:11 UTC, AjexRose commented
After testing it via addgamerule and endgamerule, the mobs despawn without the salvage component when the event ends. Either that or they already have it somewhere.

2024-01-23 22:12 UTC, AjexRose commented
also the spell book was set to safe, and the wizard hardsuit was replaced by syndicate hardsuit

2024-01-23 22:16 UTC, FoxxoTrystan reviewed
All good, tho the Syndicate Hardsuit is an Elite one and seem a bit too easy to get in my opinion but overall il say generally its fine.

2024-01-23 22:16 UTC, FoxxoTrystan commented on Resources/Locale/en-US/_NF/bluespace-events/events.ftl
> +
Hmmm Space!

2024-01-23 22:17 UTC, FoxxoTrystan approved these changes

2024-02-11 23:19 UTC, AjexRose commented
Updated to have more decals, removed the omega soap, replaced the syndicate hardsuit with AME fuel, switched power from damaged RTGs to regular RTGs, replaced the unused atmos space with a space for portable scrubbers.

2024-02-12 21:13 UTC, Cheackraze commented
> Updated to have more decals, removed the omega soap, replaced the syndicate hardsuit with AME fuel, switched power from damaged RTGs to regular RTGs, replaced the unused atmos space with a space for portable scrubbers. Also changed the file name to match current naming standards

was just looking to do some map reviews and such. Do you have any pictures of the new decaling? it was going to be my only critique of the map itself. Otherwise, I can help update this to the latest build and get this in game, however the vending machine sprite needs fixing desperately as well, if you wouldnt mind taking a look at cleaning that one up.

2024-02-12 22:12 UTC, Cheackraze commented
just tested it out a few times, the map itself looks nice, especially with the added decals. I'm only a little concerned that it will get powergamed everytime and might in the future re-arrange what items are stored in each of your vault areas. If we could just get that vending machine sprite cleaned up i'd say its good to merge

2024-02-12 22:15 UTC, AjexRose commented
Just got home from uni, so apologies for not getting back to you sooner
> just tested it out a few times, the map itself looks nice, especially with the added decals. I'm only a little concerned that it will get powergamed everytime
Most items are simple fill-in substitutes until I get more faction unique items made.
> If we could just get that vending machine sprite cleaned up i'd say its good to merge
I'll start to work on that ASAP

2024-02-13 01:13 UTC, AjexRose commented
vending machine's display sprite has been fixed at last!

2024-02-15 02:56 UTC, Cheackraze approved these changes

2024-02-15 02:57 UTC, merged