NC Crescent Update
new-frontiers-14/frontier-station-14 pull request #915
Opened 2024-01-24 11:09 UTC by ErhardSteinhauer

## About the PR
Updating NC Crescent to current mapping standards ()not much needed to changed:
- Colored pipes that missed color.
- Removed loose encryption keys.
- Replaced custom gun safe in mercenary room with T2 Gun Safe Spawner.
- Replaced some computer consoles with tabletop variants.
- Added Vacuum Markers to exposed to space tiles.
- Enabled Pilot Job.
- Moved ship.yml to Maps/_NF/Shuttles/

## Why / Balance
New mapping standards.

## Media
- [X] Not needed.

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated NC Crescent to current mapping standards.

2024-01-24 11:13 UTC, ErhardSteinhauer commented
Ship owner: @Kesiath 
(Just tagging you to make sure you're aware there's suggested changes for you ship.)

2024-01-24 14:05 UTC, TsjipTsjip requested changes
Please update `.github/mapchecker/whitelist.yml` and remove Crescen'ts entry entirely. We fixed these entries in VC, file just needs to be updated.

2024-01-24 14:14 UTC, TsjipTsjip approved these changes
Mapchecker is happy, and so am I!

2024-01-29 22:13 UTC, dvir001 approved these changes

2024-01-29 22:22 UTC, merged