Helix (Update)
new-frontiers-14/frontier-station-14 pull request #953
Opened 2024-01-30 13:28 UTC by ErhardSteinhauer

## About the PR
Updating NM Helix to current mapping standards:
- Atmos rework.
- Removed some loot.
- Replaced some consoles with tabletop variants.
- Added firelocks.
- Added blast doors to cover conveyor lines output.
- Added Vacuum Markers to exposed to space tiles.
- Moved ship.yml to Maps/_NF/Shuttles/

## Why / Balance
New mapping standards.

## Media
![2024-1-30_16 15 07](https://github.com/new-frontiers-14/frontier-station-14/assets/65374927/4eb16791-76f6-4878-9ca0-c1ecbcf53554)
- [X] I have added screenshots/videos to this PR showcasing its changes ingame.

**Changelog**
:cl: erhardsteinhauer
- tweak: Updated NM Helix to current mapping standards.

2024-01-30 13:32 UTC, KM-Catman commented
holy hell a drain AND an atmos system the Helix is finally useable

2024-02-02 06:31 UTC, MagnusCrowe requested changes
The tabletop shuttle console z-fights with the table under it, making it annoying to use.
This occurs at different camera rotations and ship rotations. 

Please either figure out a solution or replace it with a normal shuttle console.

2024-02-02 18:47 UTC, MagnusCrowe commented
apparently dvir is fixing it so dont worry about it

2024-02-02 18:47 UTC, MagnusCrowe approved these changes

2024-02-02 18:49 UTC, merged